#+title: Budget Friendly Foods
#+date: 2025-01-24T11:11:42+01:00
#+lastmod: 2025-01-24T11:11:42+01:00
# ISO 8601 date use output from
# C-u M-! date -Iseconds
#+draft: false
#+tags[]:

Source: https://www.myplate.gov/shopsimple/foods/all
# more

Im REWE Lebensmittel-Lexikon findest du Wissenswertes zu verschiedenen
Lebensmitteln, Getränken und allem was du sonst über Essen wissen
solltest.

https://www.rewe.de/lexikon/

* Früchte und Fruchtsäfte
** Apfelmus, ungesüßt, mit Zusatz von Vitamin C
** Kochbananen, reif, roh
** Heidelbeeren, roh
** Melonen, Cantaloupe, roh
** Grapefruitsaft, rot, nicht angereichert, nicht aus Konzentrat, gekühlt
** Mango, Ataulfo, geschält, roh
** Orangen, roh, Nudeln
** Pfirsiche, gelb, roh
** Birnen, roh, bartlett
** Ananas, roh
** Erdbeeren, roh
* Gemüse
** Rote Bete, roh
** Brokkoli, roh
** Karotten, reif, roh
** Blattkohl, roh
** Gurke, mit Schale, roh
** GrünBohnen, Snap, grün, roh, Gartenbohnen
** Kohl, grün, roh, Weißkohl
** Kartoffeln, goldfarben, ohne Schale, roh
** Kürbis, Sommer, grün, Zucchini, mit Schale, roh
* Hülsenfrüchte und Hülsenfruchtprodukte
** Bohnen, trocken, schwarz (0% Feuchtigkeit)
** Bohnen, trocken, Dunkelrot Niere (0% Feuchtigkeit), KidneyBohne
** Linsen, trocken
** Erdnussbutter, cremig
** Erdnüsse, roh
** GartenBohnen, BuschBohnen, Stangenbohnen, trocken, Pinto (0% Feuchtigkeit)
* Backwaren
** Brot, Vollkornbrot, handelsüblich zubereitet
* Getreide und Teigwaren
** Reis, braun, langkörnig, nicht angereichert, roh
Cargoreis, Naturreis, Vollkornreis

https://www.rewe.de/lexikon/vollkornreis/

Kann Vollkornreis auch schaden?  Trotz aller gesundheitlichen Vorteile
gibt es auch bei Vollreis eine Kehrseite der Medaille: Ökotest hat
2022 in einer Untersuchung zum wiederholten Male schädliche Stoffe in
Vollkornreis entdeckt. Denn die Randschichten des Reiskorns sind nicht
nur reich an Ballaststoffen und Mineralien. Sie speichern auch
Pestizide, Arsen, Schwermetalle und Mineralöle ein.

Laut Testergebnissen reicht es nicht, Bio-Vollkornreis zu kaufen. Auch
ökologisch hergestellte Produkte waren teilweise stark belastet. Zwar
bedeutet „bio“, dass beispielsweise keine Pestizide beim Anbau zum
Einsatz kommen dürfen. Es wird aber vermutet, dass der Reis teilweise
beim Transport kontaminiert wird. Andere Schadstoffe können beim Anbau
über den Boden in die Reispflanzen gelangen.

Ökotest rät deshalb von einem regelmäßigen Verzehr von Reis als
Vollkorn ab. Gleiches gilt für Parboiled Reis, da bei diesem
speziellen Herstellungsverfahren neben den guten Inhaltsstoffen auch
die potenziell vorhandenen Schadstoffe ins Innere des Reiskorns
befördert werden. Empfohlen wird stattdessen der Verzehr von poliertem
Basmati, weil dieser durchschnittlich weniger belastet ist.

DasBundeinstitut für Risikobewertung (BfR) erklärte in einer
Stellungnahme aus dem Jahr 2020, dass nicht grundsätzlich auf den
Verzehr von Reis verzichtet werden muss. Es wird aber empfohlen, die
Vollkorn-Variante abwechselnd mit anderen Getreidesorten in den
Speiseplan einzubauen.

Vor allem die richtige Zubereitung ist wichtig, um möglichst vielen
Schadstoffen den Garaus auszumachen, bevor der Reis auf dem Teller
landet.


** Mais, süß, gelbe und weiße Körner, frisch, roh

** Mehl, Mais, gelb, Feinmehl, angereichert
** Hafer, Vollkorn, gewalzt, altmodisch
** Pasta, Vollkorn, Mehl, Vollweizen, nicht angereichert
** Wildreis, Wasserreis, Indianerreis, Kanadischer Reis, trocken, roh
* Milch- und Eierprodukte
** Buttermilch, fettarm
** Käse, Cheddar
** Käse, Hüttenkäse, fettarm, 2% Milchfett
** Milch, fettfrei, flüssig, mit Zusatz von Vitamin A und Vitamin D (fettfrei oder entrahmt)
** Eier, Güteklasse A, groß, Vollei
** Joghurt, griechisch, einfach, fettfrei
** Natur Joghurt, normal, fettfrei
* Fisch- und Muschelprodukte
** Fisch, Thunfisch, leicht, in Wasser eingemacht, abgetropft, Feststoffe
** Fisch, Wels, Aufzucht, roh, Katzenwels
** Fisch, Lachs, Atlantik, aus Zucht, roh
** Fisch, Zanderfisch,  Glasaugenbarsch
** Fisch, Schellfisch, Tilapia, Zuchtfisch, roh
* Geflügelprodukte
** Hähnchen, Masthähnchen oder Brathähnchen, Keule, nur Fleisch, gekocht, geschmort
** Hähnchen, Schenkel, ohne Knochen, ohne Haut, roh
