#+title: Budget Friendly Foods
#+date: 2025-01-24T11:11:42+01:00
#+lastmod: 2025-01-24T11:11:42+01:00
# ISO 8601 date use output from
# C-u M-! date -Iseconds
#+draft: false
#+tags[]:

Source: https://www.myplate.gov/shopsimple/foods/all
# more

Apfelmus, ungezuckert

Bananas

Rote Bete, Dosen

Schwarze Bohnen, in Dosen

Heidelbeeren, gefroren

Brot, vollkorn

Brokkoli, gefroren

Brauner Reis, Naturreis, Vollkornreis

Buttermilch

Thunfisch in Dosen in Wasser

Cantaloupe-Melone, Zucker-Melone

Karroten

Katzenwels, Fisch

Cheddar cheese, reduced fat

Hähnchenkeule, Trommelstock, Schlägel, Unterschenkel,
Hähnchenschenkel.

Hähnchenschenkelfilet.

Blattkohl

Mais, Dosen

Maismehl

Hüttenkäse.  Hüttenkäse ist eine Frischkäsesorte. Besonderes
Kennzeichen des Hüttenkäses ist seine körnige Struktur, weswegen er
auch als körniger Frischkäse (ugs. Kugerlkäse) bezeichnet wird.

Gurke.

Noch weniger Fett hat nur die entrahmte Milch, die als Magermilch
höchstens 0,5 Prozent Fett enthalten darf.

Eggs

Grapefruit

Grapefruit is in season in winter.

Joghurt Griechischer Art.

Die Gartenbohne. auch Grüne Bohne, Schnittbohne oder österreichisch
Fisole genannt.  Sie ist in Deutschland fast immer mit dem Ausdruck
„Bohne“ gemeint, der sich aber auch auf viele andere Nutzpflanzenarten
beziehen kann. Je nach Wuchsform wird die Art auch als Buschbohne oder
Stangenbohne bezeichnet.

Weißkohl

grobes Maismehl

Die Kidneybohne, auch Indianerbohne oder Rote Bohne ist eine Sorte der Gartenbohne.

Küchen-Linse.  Rote Linse, Beluga Linsen, Rote Linsen, Teller Linsen.

Mangos

Haferflocken.

Die Okra oder der Gemüse-Eibisch (Abelmoschus esculentus) ist eine
Pflanzenart aus der Familie der Malvengewächse.

Oranges

Pasta, vollkorn

Der Pfirsich (Prunus persica) ist eine Pflanzenart aus der Gattung
Prunus innerhalb der Familie der Rosengewächse (Rosaceae). Seine
Früchte werden Pfirsiche genannt und zählen zum Steinobst.

Erdnussbutter, mitunter auch als Erdnusscreme, Erdnussmus oder
Erdnusspaste bezeichnet, ist ein energiereicher Brotaufstrich, dessen
Hauptbestandteil gemahlene Erdnüsse sind.

Erdnuss.

Birne.

Ananas.

Pintobohnen.

Natur Jogurt

Kartoffeln

Rosine

Ricotta cheese, part skim

Lachs

Erdbeere, gefroren

Zanderfisch.  Glasaugenbarsch, gefroren

Die Wassermelone (Citrullus lanatus), auch Angurie, Arbuse, Pasteke
und Zitrullengurke (früheres Synonym: Cucurbita citrullus L.) genannt.

(Schellfisch, Tilapia, Wittling)

Wasserreis, Wildreis, Indianerreis oder Kanadischer Reis

