#+title: physik
#+date: 2024-12-31T00:17:08+01:00
# do not add toc for espeak
# do not add numbering for headings
#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:nil
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:nil title:nil toc:nil todo:t |:t
#+options: html-link-use-abs-url:nil html-postamble:nil
#+options: html-preamble:nil html-scripts:nil html-style:nil
#+options: html5-fancy:nil tex:t

* Schalenmodell und Orbitalmodell des Atomes
In  Schale gibt es eine Orbitalform mit Bahnen und Platz für Elektronen.
Die Schalen werden gemischt belegt nach Pauli Prinzip.

Erste Schale hat 2 Elektronen.
Zweite Schale hat 6 Elektronen.
Dritte Schale hat 10 Elektronen.

* Zerfall von Kern
Ein Element hat Isotopen, bei der die Anzahl der Neutronen
unterschiedlich sind.

Isotopen sind instabil und zerfallen in stabile Kerne.  Das Zerfall
nennt man Radioaktivität.  Beim Zerfall entsteht Radioaktive
Strahlung.

Alphastrahlung ist ein Heliumkern und kann mit Papier abgeschirmt
werden.  Betastrahlung ist ein Elektron und kann mit Metallblech
abgeschirmt werden.  Gammastrahlung ist eletromagnetisch und kann mit
Beton und Blei abgeschirmt werden.

* Kernspaltung und Kernfusion
Bei der Kernspaltung werden Kerne in zwei Kerne aufgeteilt.  Man
braucht Neutronen als Trigger.

Bei der Kernfusion werden zwei leiche Kerne zu einem Kern
verschmolzen.  Man braucht Plasma mit hohen Temperaturen als Trigger.

* Strom
Der Strom ist die Bewegung von Elektronen in einem Leiterkabel.
Dadurch wird Ladung verschoben.

* Strom fließt im Leiter
denn im Leiter gibt es zwischen den Ionen auch freie Elektronen.  Die
freien Elektronen fließen in eine Richtung unter Einfluss der
Spannung.

Der Strom fließt mit lichtgeschwindigkeit, denn die
Elektronen schubsen sich an.

Kabel hat kleinen aber nicht null Widerstand.

In Isolatoren gibt es keine freie Elektronen.  In Halbleiter gibt es
wenige freie Elektronen.

Flüssigkeit mit Salz leitet Strom.

* Strom erzeugt Magnetfeld und Magnetfeld wirkt auf Elektronen.
Strom kann ein Magnetfeld mittels Induktion erzeugen.  Bewegung des
Leiters quer zum Magnetfeld nennt man Induktion.


Generator erzeugt Wechselstrom.  Wechselstrom ist leicht zu
transformieren.

* In Quantenmechanik
Es gibt kleinste Portion von Größen wie die Energie. Der
Welle-Teilchen-Dualismus betrifft alle Teilchen.  Das Messen verändert
das System.  Quantenmechanik ermittelt nur Wahrscheinlichkeiten.

Die Schrödingergleichung beschreibt Teilchen als Wellen.

Kopenhagener Deutung beschreibt Wellenfunktion des Teilchens als
Aufenthaltswahrscheinlichkeit.  Die Viele-Welten-Theorie ist eine
Alternativ.

* Heisenbergsche Unschärferelation
heißt, dass man den Ort und den Impuls von Quantenobjekten nicht
beliebig genau bestimmen kann.

* Relativitätstheorien

Wenn man Teilchen mit Masse beschleunigt, nimmt die Masse des
Teilchens zu.

* Äquivalenzprinzip
besagt, dass die Schwerlosigkeit und freien Fall ohne Umgebung
äquivalent sind.

* Beobachtung und Experiment
Beobachtung der Natur.  Überlegungen zu den Beobachtungen.
Abstraktion auf das Allgemeinen.  Schlüsse auf die Grundlegende
Gesetze.

Experiment ist die Isolierte Betrachtung eines Phänomens, störende
Einflüsse werden ausgeblendet.  Ergebnisse sind wiederholbar und
überprüfbar.  Bestimmt Quatitative Aussagen durch Messungen.

* Theorie und Hypothese
Hypothesen sind Vermutungen aufgrund Experimenten.

Theorie ist viele Hypothesen zur Erklärung eines Phänomens.

Modell ist eine vereinfachte Beschreibung eines Phänomens.

* Messen
ist die Bestimmung der physikalischen Größe in Einheiten und
Messfehler.

Messfehler sind zufällig und systematisch.

* Atomen
Atomen besteht aus Elektronen und ein Kern aus Protonen und Neutronen.
Das Elektron ist unteilbar.

* Grundlegende Kräfte
sind die starke und schwache Wechselwirkung, die elektromagnetische
Kraft und die Gravitationskraft.

* Newtonsche Axiomen
Erste Axiom.  Trägheit.  Der Körper ist zu träge, etwas zu ändern, und
bleibt wie er sich gerade bewegt.

Zweite Axiom.  Beschleunigung.  Eine Kraft ändert die Geschwindigkeit
des Körpers.

Dritte Axiom.  Aktio gleich Reaktio.  Übt ein Körper A eine Kraft auf
ein Körper B, so wirkt eine gleich große aber entgegengerichtete Kraft
von Körper B auf Körper A.

* Elastischen und Unelastischen Stoß
Beim Elastischen Stoß wird die mechanische Energie beim Aufprall
vollständig in mechanische Energie umgewandelt.

Beim unelastischen Stoß wird ein Teil der mechanischen Energie beim
Aufprall in Wärme und Verformung umgewandelt und die beider Körper
bewegen sich mit gemeinsamer Geschwindigkeit weiter.

* Flugzeug fliegt wegen Antrieb und Auftrieb
Für das Antrieb des Flugzeugs saugt Propeller Luft von vorne an und
stoßen sie nach hinten ab.

Für das Auftrieb wird richtige Flügelform benötigt.  Luft oberhalb
wird zusammengedrückt und strömt schneller als die Luft unterhalb des
Flügels.

* Ebbe und Flut
Ebbe und Flut treten zweimal am Tag auf.  Die Anziehungskraft der Mond
und die Fliehkraft verursacht die Ebbe und Flut.

* Die schiefe Drehachse ist der Grund für Jahreszeiten
Die Erde dreht um sich selbst. Die Drehachse der Erde ist schief.  Die
Nordhalbkugel wird im Sommer länger und intensiver von der Sonne
bestrahlt.  Die Südhalbkugel wird im Winter länger und intensiver
bestrahlt.  In den Tropen gibt es nur Regen- und Trockenzeit, denn die
Region liegt zwischen nördlichen und südlichen Wendekreisen.

* Die Erde hat Magnetfeld
wegen des Eisenkerns.  Der Kern leitet Strom und erzeugt Magnetfeld.
Der Erdmagnetfeld lenkt Hochenergieteilchen von der Sonne ab und
schützt uns.

* Treibhauseffekt der Erdatmosphäre
Die Erdatmosphäre lässt sichtbares Licht und Infrarot von der Sonne
durch und reflektiert Infrarot Wärmestrahlung von der Erdoberfläche.

* Man fühlt sich kalt, wenn aus dem Wasser kommt
denn die Wassertropfen auf der Haut verdunsten in die umgebenden Luft
und entzieht Verdampfungswärme.

* Wasser hat keine Farbe,
aber tiefes Wasser ist blau wegen des stärker Streuung des blauen
Lichtes.  Flaches Wasser sind türkis wegen der Sand unter Wasser.

* Kondenz des Wassers
Wasser wird von gasförmigen Wasserdampf in flüssiges Wasser
kondenziert.

Die Umgebung ist gesättigt mit Wasser. Es braucht irgendwas Wasser
dran kondensieren kann.

Die Wärmeluft in der Wohnung wird von kalten Brille stark abgekühlt
und die Fähigkeit, Wasser in kühle Luft aufzunehmen ist gering.

* Schall ist eine Welle, die durch Schwingung entsteht
und in einem Medium zum Verbreitung.

Charakeristische Größe: Amplitude, Frequenz, Schallenmengen

* Wolken sind weiß, denn

Wolken besteht aus kleinen Eiskristallen.  Die Eiskristallen spiegeln
weißes Licht.

* Erdhimmel ist Blau
denn Blaues Licht wird stärker gestreuut als rotes.

Die Luftteilchen streuuen Blaues Licht weg.  Am Abend ist die Sonne
rot, denn alles Blau wird weggestreut.

* Wärme
sind die Bewegung der Atome und Moleküle.

* Seewind und Landwind an der Küste
entsteht, weil am Morgen erwärmen das Wasser langsamer als die Erde
und am Abend abkühlt das Wasser langsamer als die Erde.

* Der Schall entsteht
wenn es Schwingung gibt und die Ausbreitung von Schwingung möglich
ist.  Beispiel sind Gitarrensaite und Stimmbänder.

* Wenn Instrumente denselben Ton spielen, sie hören sich nicht gleich an, denn
es gibt Grundschwingung und Oberschwingungen.  Das Verhältnis der
Amplituden der Oberschwingungen bestimmt den Klang.

* Doppler-Effekt
Bei der Bewegung der Quelle verändert sich der Ausgangspunkt.  Die
Wellenfronten vor der Quelle werden zusammengedrückt und die Frequenz
wird erhöht.  Die Wellenfronten hinter der Quelle werden
auseinandergezogen und die Frequenz wird reduziert.

Bei der Bewegung des Empfängers auf die Quelle werden die
Wellenfronten zusammengedrückt.  Bei der Bewegung des Empfängers von
der Quelle werden die Wellenfronten auseinandergezogen.

* Kaffee wird kalt
wegen Wärmeleitung, indem die Kaffee Moleküle an langsamerer
Luftteilchen stoßen und ihre Wärme abgeben.  wegen Wärmeströmung, in
dem die Kaffee Moleküle in alle Richtungen verflüchtigen.  wegen
Wärmestrahlung, indem die Kaffee Moleküle elektromagnetische Strahlung
abgeben.

Thermoskanne verhindert Wärmeleitung durch Vakkum, Wärmeströmung durch
Deckel, Wärmestrahlung durch verspiegelung.

* Lichtgeschwindigkeit ist
konstant

* Arten von Energie
Es gibt mechanische, innere, Strahlung und elektrische Energie.

Beispiele für innere Energie sind Kernenergie, Wärmeenergie, chemische
Energie.

Beispiele für Mechanische Energie sind Bewegungsenergie, Höhenenergie
und Spannenergie.

Beispiele für Strahlungsenergie sind Funkwellen, Licht und
Radioaktivität.

Beispiele für elektrische Energie sind Blitz, Elektromagnet und
Stromkreis.

* Hauptsatz der Wärmelehre
Erster Satz: in einem abgeschlossenen System ist die Zunahme der
inneren Energie gleich Wärme und mechanische Energie von außen.

Zweiter Satz: in einem abgeschlossenen System nimmt die Entropie immer
zu.

Dritter Satz: am absoluten Nullpunkt ist die Entropie gleich Null.
Absoluten Nullpunkt ist nicht erreichbar.

* Wiederholung am <2025-01-14 Tue>
Alle Aufgaben beantworten.

- Aufgabestellung durchlesen.  Wenn man Beispiele nennen soll, nennt
  man dies.
- Antworten genau die Frage, die gestellt wird.

* Sieben Physikalischen Größen und abgeleitete Größen

