#+title: vwl
#+date: 2024-12-31T00:16:32+01:00
# do not add toc for espeak
# do not add numbering for headings
#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:nil
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:nil title:nil toc:nil todo:t |:t
#+options: html-link-use-abs-url:nil html-postamble:nil
#+options: html-preamble:nil html-scripts:nil html-style:nil
#+options: html5-fancy:nil tex:t
* VWL
** Akteure
Staat ist eine Gruppe von Menschen, die bei ihrer Lebensgestaltung zusammenwirken.

** Frage 14: Gemeinsamkeiten und Unterschiede zwischen öffentlichen und privaten Haushalt.

Öffentliche und private Haushalt sind Wirtschaftssubjekte, in denen
zur Deckung eigener Bedarf Güter konsumiert werden.  Sie sind
Nachfrager der von Betrieben angebotenen Gütern.

Private Haushalte treffen Entscheidungen über Ausgaben, Wohnort und
Familienplanung.

Öffentliche Haushalte treffen Entscheidungen über Stadtplanung und
Kosten.

** Frage 13: Unterschiede und Relation zwischen Betrieb und Unternehmen

Betriebe sind Wirtschaftssubjekte, in denen zur Deckung fremder
Bedarfe Güter produziert und abgesetzt werden. Sie sind die
produktionswirtschaftliche Seite von Einzelwirtschaften.

Unternehmen sind autonome Betriebe in privatem Eigentum, die
gewinnorientiert arbeiten.  Sie sind die rechtlich-finanzielle Seite
von Einzelwirtschaften.

** Ökonomisches Prinzip
Die knappe Güter so einzusetzen, dass ihre Nutzen maximiert.

Die knappe Güter sind die Güter, die nur in begrenztem Umfang
vorhanden sind.  Die Freie Güter sind Güter, die in unbegrenztem
Umfang vorhanden sind.

Das Ökonomisches Prinzip enthält Handlungsanweisungen wie Minimum
Prinzip und Maximum Prinzip.  Ein Nutzen mit geringstmöglichen Einsatz
erzielen.

** Effizienzarten
Technische Effizienz ist die Maximierung von Produktionsmenge durch
technische Fortschritt.

Produktive Effizienz ist die Minimierung von Kosten.

Allokative Effizienz wird erreicht, wenn das Produkt Kundenwünsche
entspricht.

Soziale Effizienz wird erreicht, wenn soziale und produktive Kosten
die soziale und produktive Nutzen entsprechen.

** Marktwirtschaft
ist das Zusammenwirken aller Haushalte und Unternehmen, in der die
Güter und Dienstleistungen zugeteilt werden.
** Rolle des Staates
Der Staat sollen Rechtssicherheit gewährleisten, die Effizienz des
Marktes erhöhen und Einkommen und Wohlstand verbessern.

** Transformationsprozess
ist der Prozess wo die Faktoreinsatz durch Komination der Faktoren
Güter produziert.

** Frage 12: Gesetz der Nachfrage
bei steigendem Preis sinkt die nachgefragte Menge.  Die Gründe sind
die Einkommenseffekt: mit gleichem Einkommen kann bei reduzierten
Preis mehr gekauft werden; und die Substitutionseffekt: mit relativ
billigen Ersatzprodukt kann teure Produkt gewechselt werden.

** Gesetz des Angebots

bei steigendem Preis steigt die angebotene Menge.

** Gesetz des Angebots und Nachfrage

Der Preis passt sich an, dass der Marktgleichgewicht erreicht wird.

** Frage 8: Konjunktur
Konjunktur ist die Schwankungen der gesamtwirtschaftlichen
Kapazitätsauslastung.  Konjunkturelle Schwankungen sind unregelmäßig
und nicht prognostizierbar.  Der Produktionsrückgang ist mit einem
Anstieg der Arbeitslosigkeit verknüpft.

Der Indikator von Konjunktur ist das Bruttoinlandsprodukt.  Das
Bruttoinlandsprodukt ist der Marktwert aller für den Endverbrauch
bestimmten Waren und Diestleistungen in einem Land.

Das Bruttoinlandsprodukt ist gleich Verbrauch plus Investition plus
Staatsausgaben plus Nettoexporte.

** Frage 11: Definition von Arbeitslos und Erwerbslos
Jemand ist Arbeitslos, wenn er arbeiten kann und zum vorherrschenden
Lohnsatz zur Verfügung steht und keine Arbeit hat.


Jemand ist Erwerbslos, wenn er gemäß dem internationalen Kriterium
arbeitslos ist.
** Frage 10: Erwerbslosenquote
wird durch das statistische Bundesamt bestimmt und dient dem
internationalen Vergleich.

Arbeitslosenquote wird durch die Bundesagentur für Arbeit bestimmt und
dient dem nationalen Orientierung.

** Export und Import
Export ist im Inland produziert, ins Ausland verkaufte Produkte.

Import ist im Ausland produziert, im Inland verkaufte Produkte.

** Frage 9: Inflation und Inflationsrate
Inflation ist die Steigerung von Preisen für Waren und
Dienstleistungen mit der Zeit, ohne dass dies auf Mengen- oder
Qualitätsveränderungen zurückzuführen ist.

Inflation wird mit die Inflationsrate gemessen.  Sie ist ein
gewichteter Mittelwert von Preisänderungen der typischer Ausgaben
eines Haushalts.
** Preisbildung
1. Angebot (Nachfrage) steigt (sinkt) von M1 zu M2 entlang des
   Preisniveaus.  Es besteht Angebots (Nachfrage) überhang.
2. Preis sinkt (steigt) von P0 zu P1.
3. Nachfragemenge steigt von M3 zu M4.  Angebotsmenge sinkt von M2 zu M3.
* BWL
** Konstitutive Entscheidungen
sind seltene Führungsentscheidungen.

** Frage 5: Rechtsform
|        | Haftung          | Mindest | Kontroll | GuV         | Kapitalbeschaffung    |
| Einzel | unbes            | kein    |          |             | Kredit, kein Extern   |
| OHG    | unbes            | kein    |          | nach Anteil | Kredit, Einlage       |
| KG     |                  |         |          |             | Kredit, Einlage       |
| AG     | betriebsvermögen | 50000   |          | nach Anteil | Kredit, Aktien        |
| GmbH   | betriebsvermögen | 25000   |          | nach Anteil | Kredit, Anteilverkauf |

** Frage 6: Gemeinschaftsunternehmen
ist eine Form der Zusammenarbeit zwischen mehreren unabhängigen
Unternehmen, die ein rechtlich selbständiges Unternehmen gegründet mit
dem Ziel, Aufgaben im gemeinsamen Interesse der
Gesellschaftsunternehmen auszuführen.
** Frage 15: Personengesellschaften und Kapitalgesellschaften
Personengesellschaften sind keine juristischen Personen.  Für
Verbindlichkeiten haftet der Gesellschafter unbeschränkt.

Eine Kapitalgesellschaft ist eine juristische Person.  Für
Verbindlichkeiten haftet nur die Betriebsvermögen.  Der Bestand der
Gesellschaft ist unabhängig von der Person der Gesellschafter.
** Frage 7: Kooperation
Ziel der Unternehmenskooperation ist Wirtschaftlichkeit durch
Rationalisation, Risiken durch Diversifikation, Verhandlungsmacht
durch Konzentration.

Im Bereich Beschaffung, Finanz, Produktion, Absatz und Steuerliche.

Risikostreuung durch Diversifikation ist der Zusamenschluss mit
anderen Unternehmen, die entweder Produkte herstellen, die in
sachlichem Zusammenhang mit den eigenen Produkten stehen, oder einer
Abstazstufe angehören oder sich wechselseitig mit eigenen Produkten
ergänzen.

** Liquidation
erfolgt freiwilig wegen Erfüllung des Zieles oder Zwang wegen Zahlungsunfähigkeit.
** Führung
** Frage 21: Intrinsische und Extrinsische Motivation
Intrinsische Motivation sind Leistungs-, Kompetenz- und
Geselligkeitsmotive.

Man macht etwas um seiner selbst willen.  Man
findet Befriedigung in der Arbeit.

Man streben nach
verantwortungsvoller Tätigkeit, nach Entscheidungsfreiheit, nach
persönlichen Entwicklung.

Extrinsische Motivation sind Geld-, Sicherheit- und Statusmotive.

Man macht etwas für die Folgen der Arbeit.

Man streben nach Gehaltserhöhung, vermeide Bestrafung und
Gehaltsreduzierung.

** Frage 1: Fokus der Nachfrageorientierte Personalentwicklung

Co-Creation auf Teamebene.

Kontext: komplexe Bedingungen und ihre Auswirkungen zu erkennen.

Entwicklungsmaßnahme: Fehlerrate hat sich verbessert.
** Frage 2: Cafeteria Vergütungssystem
Der Mitarbeiter wählt selbst, welche Sozialleistung der Unternehmen er
erhalten will und erhält dabei Punkte.
** Führungsstill
wird nach Art der Willensbildung beurteilt.  Es gibt autoritärer
Führungsstil, der Aufgabenorientiert ist.  Es gibt partizipativer
Führungsstil, der Personenorientiert ist.

** Organisation
** Frage 22: Organisationsgrad
Organisationsgrad beschreibt wie viel Regel in einer Organsation gibt.
Je mehr Regeln, desto weniger spontane Handlungsweisen im
Lestungsprozess.  Regeln macht vor allem Sinn, wo sich Aufgaben
wiederholen.  Variabler Tätigkeiten benötigt Freiraum und weniger
Regeln.

Überorganisation und Unterorganisation ist vorhanden, falls der
Organisationsgrad nicht optimal ist.
** Organisationsgrad
Funktional, Divisional, Matrix.

** Frage 26, 27: Macht
Sanktionsmacht: Der Beeinflusste handelt im Sinne des Beeinflussenden,
da er sich einer Bestrafung entziehen möchte.

Expertenmacht: Basiert auf der fachlichen und sachlichen Überlegenheit.

Informationsmacht: Basiert auf der Kontrolle über die Nutzung und
Verteilung von Informationen.

Identifikationsmacht: Basiert auf der Identifikation des Beeinflussten
mit dem Beeinflussenden (Vorbild).

** Frage 24: Ablauf eines Projekts nach dem Scrum Methode
Der Product Owner erstellt das Product Backlog.

Der Sprint beginnt mit dem Sprint Planning. Während dieses Events
entscheidet das Scrum Team, woran es in diesem Sprint arbeiten wird.

Das Sprint Backlog wird erstellt: Die Prognose der bevorstehenden
Arbeit für diesen Sprint, um das Sprint-Ziel zu erreichen.

Der Scrum Master verantwortet die Effektivität des Scrum Teams.

Die Entwickler schaffen jeden Sprint ein Inkrement.

Während des Sprints gibt es alle 24 Stunden ein Daily Scrum.

Am Ende des Sprints organisiert das Scrum Team für die Stakeholder ein
Sprint-Review.

Nach dem Sprint-Review nutzt das Scrum Team die Sprint Retrospektive,
um über Arbeit nachzudenken.

** Frage 20, 25: Dimensionen der agile Organisation
Strukturelle Dimension ist strukturell Kunden orientiert.  Die
Organisation strukturiert sich nach Teams und auf Kunden ausgerichtet.

Strategische Dimension haben eine von Außen nach Innen Denkweise.  Der
Kunde steht im Mittelpunkt des Denkens.  Die Strategie wird auf Kunde
ausgerichtet.  Erfolg wird als KundennOButzen verstanden.

Prozessuale Dimension: komplett Unternehmen arbeiten nach agilen Prinzip.

Dimension der Führung sind verteilte Führung und Ermächtigte Führung.
Führungsaufgaben werden auf mehrere Schultern geteilt.  Der
Mitarbeiter wird Ermächtigt, selbst entscheiden zu können und
selbstverantwortlich handeln zu dürfen.

Dimension der HR-Instrumente: HR sollen Transformation nach Agil helfen.

Kulturelle Dimension: Agile Organisation benötigt
Vertrauen. Management vertraut Teams, organisiert zu sein.  Ihnen wird
vertraut im Sinne der Organisation zu handeln.  Vertrauen ersetzt
Regeln.
** Frage 23: Herausforderungen der Umwandlung von pyramid zu agil Netzwerk.
Konflikte durch Abbau von Machthierarchien.
** Frage 4: Ziele der Personalwirtschaft
sind wirtschaftlich die Versorgung des Unternehmens mit geeigneten
Personal unter Berücksichtigung des Ökonomischen Prinzips.

Soziale Ziele sind die bestmögliche Gestaltung der Arbeitsumstände für
die Mitarbeiter.

** Frage 3: Vor und Nachteile der Personalbeschaffung
Vorteile: Motivierung durch Aufstiegschancen, Besseres Betriebsklima,
Geringeres Risiko, Geschwindigkeit, Geringe Beschaffungskosten, Kurze
Einarbeitungszeit

Nachteile: keine neuen Ideen durch neue Mitarbeitern, Geringe Auswahl,
Demotivation, Rivalität.

** Leistung
** Beschaffungsziele
Materialien in richtigen Qualität, zum richtigen Preis beschaffen.
Streben nach Wirtschaftlichkeit.
** Frage 17, 18: Fertigungstypen
Massenfertigung ist unbegrenzt viele Einheiten eines Produkte auf
gleichen Anlagen.

Sortenfertigung: ist mehrere Einheiten verschiedener Produkte auf
gleichen Anlagen.

Serienfertigung ist mehrere Einheiten verschiedener Produkte auf
verschiedener Anlagen.

Chargenfertigung ist bei gleichem Materialeinsatz aufgrund nicht
beeinflussbarer Bedingungen unterschiedliche Ergebnisse erzielt
werden.

** Frage 19: Fertigungsverfahren
Werkstattfertigung sind Maschinen an einem Ort.

Fließfertigung sind Maschinen so angeordnet, dass Arbeitsgänge
aufeinander folgen.

Gruppenfertigung wird Funktionsgruppen angeordnet.

Baustellenfertigung wird an den Baustellen gefertigt.
** Finanz
** Frage 16: Kennzahl der Liquidität ersten Grades
Barliquidität ist eine Kennzahl zur Beurteilung der
Zahlungsfähigkeit (Liquidität) eines Unternehmens.

Der Aussagekraft dieser Kennzahl ist begrenzt, da diese Vergangenheitsdaten
und zeitpunktbezogen ist.
