#+title: recht
#+date: 2024-12-31T00:30:12+01:00
* Notizen
Arb -> Landlicher Arbeitsgericht LAG -> Bundlicher Arbeitsgericht

Amtsgericht -> LG -> BAH

ArbG -> LAG -> BAG

AG -> LG (-> OLG über 5000 Euro) -> BAH

Grundlagen des Rechts (ende)

1. Gerichtsinstanzen (pyramide)
2. normenhierachie
gerichtaufbau
privatrechtanwaltskosten selbst zu tragen

gerichtsaufbau

zivilprozess und arbeitsgericht, unterschied

arbeitsgerichtsprozesses (geringe gerichtskosten)


Bügerliches Recht

1. BGB

taschenguide arbeitsrecht

abschnitt 8 einzelne schuldverhältnisses

gegenseitige Verträge

Schuldverhältnisse ohne

Leihe 598ff / Bürgschaft / Schenkung

Titel 27 Unerlaubte Handlungen

823 Deliktrecht

812

--------------------------------------

die begründung des arbeitvertrag erfordert nicht schriftform
die kündigung die beendigung, schriftform erforderlich

whatsapp genügt nicht die schriftform

die kündigung im original / vollmacht im original 

ss 126

ist durch gesetz schriftliche form vorgeschrieben, so muss die Urkunde
von dem Aussteller eigenhändig durch Namensunterschrift oder mittels
notariell beglaubigten Handzeichen unterzeichnet werden.

elektronisch 123aff soll die gesetzlich vorgeschriebene schriftliche
form durch die elektronische form ersetzt werden, so muss der
aussteller der erklärung dieser seinen Namen hinzufügen und das

E-Mail

TzBfG 14
die befristung eines arbeitsvertrages bedarf zu ihrer wirksamkeitder
schriftform

beglaubigte Kopie:  öffentliche / notarische beglaubigung

notarielle urkundung / notarielle beglaubigung

urkundung : man will wissen, dass das inhalt korrekt ist
beglaubigung: notar bestätigt lediglich, dass die kopie identisch ist


WILLENSERKLÄRUNG
schriftlcihe 126
elektronische 126a
textform
notarielle beurkundung / beglaubigung
handschlag
konkludent
mündlich
schweigen (ausnahme)

ausnahme schweigen  hgb 362
Übungsklausur, nächster Woche.

Wann kann man Willenserklärung wiederrufen?

Gesetzliches Widerrufsrecht vierzehntag für Verbraucher. 312 BGB.

Mängelfreie Sache: 434 BGB, wenn Montage erforderlich ist, kann die
Mängelfreiheit auch an der Anleitung liegen.

Nacherfüllung: 439 Nacherfüllung.

Kaufpreis mindern, Schadenersatz verlangen.

Anfechtung: eigene Willenserklärung wieder kaputt machen:  119 BGB,
Anfechtbarkeit wegen Irrtums.

original oder gefälschter bilder.

Übermittlungsirrtum.

Eigenschaftsirrtum.  Inhaltsirrtum.
Motivesirrtum. Übermittlungsirrtum.

Anfechtung muss ohne schuldhaftes Zögern (unverzüglich)

In Arbeitsverhältnis kommt Anfechtung wegen Irrtum nicht vor.

Anfechtbarkeit wegen Täuschung oder Drohung.

Falls Arbeitsverhältnis wegen Täuschung entsteht, dann ist der
Arbeitsvertrag vom Anfang nichtig.

Wegen arglistige Täuschung: viel längere Frist: ganzesJahres, viel
länger als sonstige situation

geschäftsfähigkeit: 104 BGB wer nicht das siebente Lebensjahr vollendet hat,
wer sich in einem die freie Willensbestimmung ausschließenden Zustand kran


SECHS BLÄTTER GESETZE BRAUCHS DU FÜR DIE KLAUSUR
* Kursinhalte
** Grundlagen des deutschen Rechts  incl. Gerichtssysteme
** Bürgerlicher Recht
Buch von Dr. Julia Preußer
- BGB, 1.+2. Buch - Allgemeiner Teil
- Schuldrecht
- Besonderen Schuldrecht
** Arbeitsrecht ArbR
Taschenguide Arbeitsrecht von Dr. Küfner-Schmitt
*** Arbeitsverhaltnis
- Begründung
- Inhalt
- Beendigung (Kündigungsschutz)
- Befristung, Teilzeit, Aushilfe, Probe
** Handelsrecht
von Dr. Krimphove
- Kaufmannseigenschaft
- die Firma
- Geschäftsabschlüsse (Schweigen, Bestätigungsschreiben, Hilfspersonen)
- Handelsgeschäfte (nur Handelskauf)
*** Begriffe
- Selbstständiger
- Unternehmer
- Gewerbetreibender
- Freiberufler
- Urproduzent
- Kaufmann
  https://de.wikipedia.org/wiki/Kaufmann_(HGB)

** Gesellschaftrecht
- Rechtsformen von Unternehmen
- Einstieg ins Verwaltungsrecht

* Klausur
- Skript/Buch lesen
- hochgeladenen Dateien zur Kenntnis nehmen
- später ist eine Datei mit den wichtigsten Gesetzen für dir Klausur
  zum Selbstausdrucken verfügbar

* _Bürgerliches Gesetzbuch (BGB)_

* § 611  Vertragstypische Pflichten beim Dienstvertrag

(1) Durch den Dienstvertrag wird derjenige, welcher Dienste zusagt, zur
Leistung der versprochenen Dienste, der andere Teil zur Gewährung der
vereinbarten Vergütung verpflichtet.

(2) Gegenstand des Dienstvertrags können Dienste jeder Art sein.

* § 611a Arbeitsvertrag\\
(*1) 1Durch den Arbeitsvertrag wird der Arbeitnehmer im Dienste eines
anderen zur Leistung weisungsgebundener, fremdbestimmter Arbeit in
persönlicher Abhängigkeit verpflichtet. 2Das Weisungsrecht kann Inhalt,
Durchführung, Zeit und Ort der Tätigkeit betreffen. 3Weisungsgebunden
ist, wer nicht im Wesentlichen frei seine Tätigkeit gestalten und seine
Arbeitszeit bestimmen kann. 4Der Grad der persönlichen Abhängigkeit
hängt dabei auch von der Eigenart der jeweiligen Tätigkeit ab. 5Für die
Feststellung, ob ein Arbeitsvertrag vorliegt, ist eine Gesamtbetrachtung
aller Umstände vorzunehmen. 6Zeigt die tatsächliche Durchführung des
Vertragsverhältnisses, dass es sich um ein Arbeitsverhältnis handelt,
kommt es auf die Bezeichnung im Vertrag nicht an.\\
(2) Der Arbeitgeber ist zur Zahlung der vereinbarten Vergütung
verpflichtet.

* § 622  Kündigungsfristen bei Arbeitsverhältnissen

(1) Das Arbeitsverhältnis eines Arbeiters oder eines Angestellten
(Arbeitnehmers) kann mit einer Frist von vier Wochen zum Fünfzehnten
oder zum Ende eines Kalendermonats gekündigt werden.

(2) 1 Für eine Kündigung durch den Arbeitgeber beträgt die
Kündigungsfrist, wenn das Arbeitsverhältnis in dem Betrieb oder
Unternehmen

1. zwei Jahre bestanden hat, einen Monat zum Ende eines Kalendermonats,

2. fünf Jahre bestanden hat, zwei Monate zum Ende eines Kalendermonats,

3. acht Jahre bestanden hat, drei Monate zum Ende eines Kalendermonats,

4. zehn Jahre bestanden hat, vier Monate zum Ende eines Kalendermonats,

5. zwölf Jahre bestanden hat, fünf Monate zum Ende eines Kalendermonats,

6. 15 Jahre bestanden hat, sechs Monate zum Ende eines Kalendermonats,

7. 20 Jahre bestanden hat, sieben Monate zum Ende eines Kalendermonats.

(3) Während einer vereinbarten Probezeit, längstens für die Dauer von
sechs Monaten, kann das Arbeitsverhältnis mit einer Frist von zwei
Wochen gekündigt werden.

(4) 1 Von den Absätzen 1 bis 3 abweichende Regelungen können durch
Tarifvertrag vereinbart werden. 2Im Geltungsbereich eines solchen
Tarifvertrags gelten die abweichenden tarifvertraglichen Bestimmungen
zwischen nicht tarifgebundenen Arbeitgebern und Arbeitnehmern, wenn ihre
Anwendung zwischen ihnen vereinbart ist.

(5) 1 Einzelvertraglich kann eine kürzere als die in Absatz 1 genannte
Kündigungsfrist nur vereinbart werden,

1. wenn ein Arbeitnehmer zur vorübergehenden Aushilfe eingestellt ist;
   dies gilt nicht, wenn das Arbeitsverhältnis über die Zeit von drei
   Monaten hinaus fortgesetzt wird;

2. wenn der Arbeitgeber in der Regel nicht mehr als 20 Arbeitnehmer
   ausschließlich der zu ihrer Berufsbildung Beschäftigten beschäftigt
   und die Kündigungsfrist vier Wochen nicht unterschreitet.

2 Bei der Feststellung der Zahl der beschäftigten Arbeitnehmer sind
teilzeitbeschäftigte Arbeitnehmer mit einer regelmäßigen
wöchentlichen Arbeitszeit von nicht mehr als 20 Stunden mit 0,5 und
nicht mehr als 30 Stunden mit 0,75 zu berücksichtigen. 3 Die
einzelvertragliche Vereinbarung längerer als der in den Absätzen 1 bis
3 genannten Kündigungsfristen bleibt hiervon unberührt.

(6) Für die Kündigung des Arbeitsverhältnisses durch den Arbeitnehmer
darf keine längere Frist vereinbart werden als für die Kündigung
durch den Arbeitgeber.

* § 623  Schriftform der Kündigung

Die Beendigung von Arbeitsverhältnissen durch Kündigung oder
Auflösungsvertrag bedürfen zu ihrer Wirksamkeit der Schriftform; die
elektronische Form ist ausgeschlossen.

* § 626  Fristlose Kündigung aus wichtigem Grund

(1) Das Dienstverhältnis kann von jedem Vertragsteil aus wichtigem
Grund ohne Einhaltung einer Kündigungsfrist gekündigt werden, wenn
Tatsachen vorliegen, auf Grund derer dem Kündigenden unter
Berücksichtigung aller Umstände des Einzelfalles und unter Abwägung
der Interessen beider Vertragsteile die Fortsetzung des
Dienstverhältnisses bis zum Ablauf der Kündigungsfrist oder bis zu der
vereinbarten Beendigung des Dienstverhältnisses nicht zugemutet werden
kann.

(2) 1 Die Kündigung kann nur innerhalb von zwei Wochen erfolgen. 2 Die
Frist beginnt mit dem Zeitpunkt, in dem der Kündigungsberechtigte von
den für die Kündigung maßgebenden Tatsachen Kenntnis erlangt. 3 Der
Kündigende muss dem anderen Teil auf Verlangen den Kündigungsgrund
unverzüglich schriftlich mitteilen.

* _Kündigungsschutzgesetz (KSchG)_

* § 1  Sozial ungerechtfertigte Kündigungen

(1) Die Kündigung des Arbeitsverhältnisses gegenüber einem
Arbeitnehmer, dessen Arbeitsverhältnis in demselben Betrieb oder
Unternehmen ohne Unterbrechung länger als sechs Monate bestanden hat,
ist rechtsunwirksam, wenn sie sozial ungerechtfertigt ist.

(2) 1 Sozial ungerechtfertigt ist die Kündigung, wenn sie nicht durch
Gründe, die in der Person oder in dem Verhalten des Arbeitnehmers
liegen, oder durch dringende betriebliche Erfordernisse, die einer
Weiterbeschäftigung des Arbeitnehmers in diesem Betrieb entgegenstehen,
bedingt ist. 2 Die Kündigung ist auch sozial ungerechtfertigt, wenn

1. in Betrieben des privaten Rechts

1. a)  die Kündigung gegen eine Richtlinie nach § 95 des
   Betriebsverfassungsgesetzes verstößt,

2. b)  der Arbeitnehmer an einem anderen Arbeitsplatz in demselben
   Betrieb oder in einem anderen Betrieb des Unternehmens
   weiterbeschäftigt werden kann

und der Betriebsrat oder eine andere nach dem Betriebsverfassungsgesetz
insoweit zuständige Vertretung der Arbeitnehmer aus einem dieser
Gründe der Kündigung innerhalb der Frist des § 102 Abs. 2 Satz 1 des
Betriebsverfassungsgesetzes schriftlich widersprochen hat,

2. in Betrieben und Verwaltungen des öffentlichen Rechts

1. a)  die Kündigung gegen eine Richtlinie über die personelle Auswahl
   bei Kündigungen verstößt,

2. b)  der Arbeitnehmer an einem anderen Arbeitsplatz in derselben
   Dienststelle oder in einer anderen Dienststelle desselben
   Verwaltungszweiges an demselben Dienstort einschließlich seines
   Einzugsgebietes weiterbeschäftigt werden kann

und die zuständige Personalvertretung aus einem dieser Gründe
fristgerecht gegen die Kündigung Einwendungen erhoben hat, es sei denn,
daß die Stufenvertretung in der Verhandlung mit der übergeordneten
Dienststelle die Einwendungen nicht aufrechterhalten hat.

3 Satz 2 gilt entsprechend, wenn die Weiterbeschäftigung des
Arbeitnehmers nach zumutbaren Umschulungs- oder Fortbildungsmaßnahmen
oder eine Weiterbeschäftigung des Arbeitnehmers unter geänderten
Arbeitsbedingungen möglich ist und der Arbeitnehmer sein
Einverständnis hiermit erklärt hat.

4 Der Arbeitgeber hat die
Tatsachen zu beweisen, die die Kündigung bedingen.

(3) 1 Ist einem Arbeitnehmer aus dringenden betrieblichen Erfordernissen
im Sinne des Absatzes 2 gekündigt worden, so ist die Kündigung
trotzdem sozial ungerechtfertigt, wenn der Arbeitgeber bei der Auswahl
des Arbeitnehmers die Dauer der Betriebszugehörigkeit, das Lebensalter,
die UnterhaltspBlichten und die Schwerbehinderung des Arbeitnehmers
nicht oder nicht ausreichend berücksichtigt hat; auf Verlangen des
Arbeitnehmers hat der Arbeitgeber dem Arbeitnehmer die Gründe
anzugeben, die zu der getroffenen sozialen Auswahl geführt haben. 2 In
die soziale Auswahl nach Satz 1 sind Arbeitnehmer nicht einzubeziehen,
deren Weiterbeschäftigung, insbesondere wegen ihrer Kenntnisse,
Fähigkeiten und Leistungen oder zur Sicherung einer ausgewogenen
Personalstruktur des Betriebes, im berechtigten betrieblichen Interesse
liegt. 3 Der Arbeitnehmer hat die Tatsachen zu beweisen, die die
Kündigung als sozial ungerechtfertigt im Sinne des Satzes 1 erscheinen
lassen.

(4) Ist in einem Tarifvertrag, in einer Betriebsvereinbarung nach § 95
des Betriebsverfassungs­gesetzes oder in einer entsprechenden Richtlinie
nach den Personalvertretungsgesetzen festgelegt, wie die sozialen
Gesichtspunkte nach Absatz 3 Satz 1 im Verhältnis zueinander zu
bewerten sind, so kann die Bewertung nur auf grobe Fehlerhaftigkeit
überprüft werden.

(5) 1 Sind bei einer Kündigung auf Grund einer Betriebsänderung nach §
111 des Betriebs­verfassungsgesetzes die Arbeitnehmer, denen gekündigt
werden soll, in einem Interessenausgleich zwischen Arbeitgeber und
Betriebsrat namentlich bezeichnet, so wird vermutet, dass die Kündigung
durch dringende betriebliche Erfordernisse im Sinne des Absatzes 2
bedingt ist.2 Die soziale Auswahl der Arbeitnehmer kann nur auf grobe
Fehlerhaftigkeit überprüft werden. 3 DieSätze 1 und 2 gelten nicht,
soweit sich die Sachlage nach Zustandekommen des Interessenausgleichs
wesentlich geändert hat. 4Der Interessenausgleich nach Satz 1 ersetzt
die Stellungnahme des Betriebsrates nach § 17 Abs. 3 Satz 2.

* § 23  Geltungsbereich

(1) 1 Die Vorschriften des Ersten und Zweiten Abschnitts gelten für
Betriebe und Verwaltungen des privaten und des öffentlichen Rechts,
vorbehaltlich der Vorschriften des § 24 für die Seeschiffahrts-,
Binnenschiffahrts- und Luftverkehrsbetriebe. 2 Die Vorschriften des
Ersten Abschnitts gelten mit Ausnahme der §§ 4 bis 7 und des § 13 Abs. 1
Satz 1 und 2 nicht für Betriebe und Verwaltungen, in denen in der Regel
fünf oder weniger Arbeitnehmer ausschließlich der zu ihrer
Berufsbildung Beschäftigten beschäftigt werden. 3 In Betrieben und
Verwaltungen, in denen in der Regel zehn oder weniger Arbeitnehmer
ausschließlich der zu ihrer Berufsbildung Beschäftigten beschäftigt
werden, gelten die Vorschriften des Ersten Abschnitts mit Ausnahme der
§§ 4 bis 7 und des § 13 Abs. 1 Satz 1 und 2 nicht für Arbeitnehmer,
deren Arbeitsverhältnis nach dem 31. Dezember 2003 begonnen hat; diese
Arbeitnehmer sind bei der Feststellung der Zahl der beschäftigten
Arbeitnehmer nach Satz 2 bis zur Beschäftigung von in der Regel zehn
Arbeitnehmern nicht zu berücksichtigen. 4 Beider Feststellung der Zahl
der beschäftigten Arbeitnehmer nach den Sätzen 2 und 3 sind
teilzeitbeschäftigte Arbeitnehmer mit einer regelmäßigen
wöchentlichen Arbeitszeit von nicht mehr als 20 Stunden mit 0,5 und
nicht mehr als 30 Stunden mit 0,75 zu berücksichtigen.

(2) 1 Die Vorschriften des Dritten Abschnitts gelten für Betriebe und
Verwaltungen des privaten Rechts sowie für Betriebe, die von einer
öffentlichen Verwaltung geführt werden, soweit sie wirtschaftliche
Zwecke verfolgen. 2 Sie gelten nicht für Seeschiffe und ihre Besatzung.

* _Teilzeit- und Befristungsgesetz (TzBfG)_

* § 14 Zulässigkeit der Befristung

(1) 1 Die Befristung eines Arbeitsvertrages ist zulässig, wenn sie
durch einen sachlichen Grund gerechtfertigt ist. 2 Ein sachlicher Grund
liegt insbesondere vor, wenn

1. der betriebliche Bedarf an der Arbeitsleistung nur vorübergehend
   besteht,

2. die Befristung im Anschluss an eine Ausbildung oder ein Studium
   erfolgt, um den Übergang des Arbeitnehmers in eine
   Anschlussbeschäftigung zu erleichtern,

3. [@3] der Arbeitnehmer zur Vertretung eines anderen Arbeitnehmers
   beschäftigt wird,

4. die Eigenart der Arbeitsleistung die Befristung rechtfertigt,

5. die Befristung zur Erprobung erfolgt,

6. in der Person des Arbeitnehmers liegende Gründe die Befristung
   rechtfertigen,

7. der Arbeitnehmer aus Haushaltsmitteln vergütet wird, die
   haushaltsrechtlich für eine befristete Beschäftigung bestimmt sind,
   und er entsprechend beschäftigt wird oder

8. die Befristung auf einem gerichtlichen Vergleich beruht.

(2) 1 Die kalendermäßige Befristung eines Arbeitsvertrages ohne
Vorliegen eines sachlichen Grundes ist bis zur Dauer von zwei Jahren
zulässig; bis zu dieser Gesamtdauer von zwei Jahren ist auch die
höchstens dreimalige Verlängerung eines kalendermäßig befristeten
Arbeitsvertrages zulässig. 2 Eine Befristung nach Satz 1 ist nicht
zulässig, wenn mit demselben Arbeitgeber bereits zuvor ein befristetes
oder unbefristetes Arbeitsverhältnis bestanden hat. 3 Durch
Tarifvertrag kann die Anzahl der Verlängerungen oder die Höchstdauer
der Befristung abweichend von Satz 1 festgelegt werden.4 Im
Geltungsbereich eines solchen Tarifvertrages können nicht
tarifgebundene Arbeitgeber und Arbeitnehmer die Anwendung der
tariBlichen Regelungen vereinbaren.

(2a) 1 In den ersten vier Jahren nach der Gründung eines Unternehmens
ist die kalendermäßige Befristung eines Arbeitsvertrages ohne Vorliegen
eines sachlichen Grundes bis zur Dauer von vier Jahren zulässig; bis zu
dieser Gesamtdauer von vier Jahren ist auch die mehrfache Verlängerung
eines kalendermäßig befristeten Arbeitsvertrages zulässig. 2 Dies gilt
nicht für Neugründungen im Zusammenhang mit der rechtlichen
Umstrukturierung von Unternehmen und Konzernen.3 Maßgebend für den
Zeitpunkt der Gründung des Unternehmens ist die Aufnahme einer
Erwerbstätigkeit, die nach § 138 der Abgabenordnung der Gemeinde oder
dem Finanzamt mitzuteilen ist. 4 Auf die Befristung eines
Arbeitsvertrages nach Satz 1 Bindet Absatz 2 Satz 2 bis 4 entsprechende
Anwendung.

(3) 1 Die kalendermäßige Befristung eines Arbeitsvertrages ohne
Vorliegen eines sachlichen Grundes ist bis zu einer Dauer von fünf
Jahren zulässig, wenn der Arbeitnehmer bei Beginn des befristeten
Arbeitsverhältnisses das 52. Lebensjahr vollendet hat und unmittelbar
vor Beginn des befristeten Arbeitsverhältnisses mindestens vier Monate
beschäftigungslos im Sinne des § 138 Absatz 1 Nummer 1 des Dritten
Buches Sozialgesetzbuch gewesen ist, Transferkurzarbeitergeld bezogen
oder an einer öffentlich geförderten Beschäftigungsmaßnahme nach dem
Zweiten oder Dritten Buch Sozialgesetzbuch teilgenommen hat. 2 Bis zu
der Gesamtdauer von fünf Jahren ist auch die mehrfache Verlängerung
des Arbeitsvertrages zulässig.

(4) Die Befristung eines Arbeitsvertrages bedarf zu ihrer Wirksamkeit
der Schriftform.

* § 15  Ende des befristeten Arbeitsvertrages

(1) Ein kalendermäßig befristeter Arbeitsvertrag endet mit Ablauf der
vereinbarten Zeit.

(2) Ein zweckbefristeter Arbeitsvertrag endet mit Erreichen des Zwecks,
frühestens jedoch zwei Wochen nach Zugang der schriftlichen
Unterrichtung des Arbeitnehmers durch den Arbeitgeber über den
Zeitpunkt der Zweckerreichung.

(3) Ein befristetes Arbeitsverhältnis unterliegt nur dann der
ordentlichen Kündigung, wenn dies einzelvertraglich oder im anwendbaren
Tarifvertrag vereinbart ist.

(4) 1 Ist das Arbeitsverhältnis für die Lebenszeit einer Person oder
für längere Zeit als fünf Jahre eingegangen, so kann es von dem
Arbeitnehmer nach Ablauf von fünf Jahren gekündigt werden.

2 Die Kündigungsfrist beträgt sechs Monate.

(5) Wird das Arbeitsverhältnis nach Ablauf der Zeit, für die es
eingegangen ist, oder nach Zweckerreichung mit Wissen des Arbeitgebers
fortgesetzt, so gilt es als auf unbestimmte Zeit verlängert, wenn der
Arbeitgeber nicht unverzüglich widerspricht oder dem Arbeitnehmer die
Zweckerreichung nicht unverzüglich mitteilt.

* § 16  Folgen unwirksamer Befristung

1 Ist die Befristung rechtsunwirksam, so gilt der befristete
Arbeitsvertrag als auf unbestimmte Zeit geschlossen; er kann vom
Arbeitgeber frühestens zum vereinbarten Ende ordentlich gekündigt
werden, sofern nicht nach § 15 Abs. 3 die ordentliche Kündigung zu
einem früheren Zeitpunkt möglich ist. 2 Ist die Befristung nur wegen
des Mangels der Schriftform unwirksam, kann der Arbeitsvertrag auch vor
dem vereinbarten Ende ordentlich gekündigt werden.

* _Handelsgesetzbuch (HGB)_

* § 1

(1) Kaufmann im Sinne dieses Gesetzbuchs ist, wer ein Handelsgewerbe
betreibt.

(2) Handelsgewerbe ist jeder Gewerbebetrieb, es sei denn, daß das
Unternehmen nach Art oder Umfang einen in kaufmännischer Weise
eingerichteten Geschäftsbetrieb nicht erfordert.

* § 2

1 Ein gewerbliches Unternehmen, dessen Gewerbebetrieb nicht schon nach §
1 Abs. 2 Handelsgewerbe ist, gilt als Handelsgewerbe im Sinne dieses
Gesetzbuchs, wenn die Firma des Unternehmens in das Handelsregister
eingetragen ist. 2 Der Unternehmer ist berechtigt, aber nicht
verpflichtet, die Eintragung nach den für die Eintragung kaufmännischer
Firmen geltenden Vorschriften herbeizuführen. 3 Ist die Eintragung
erfolgt, so Bindet eine Löschung der Firma auch auf Antrag des
Unternehmers statt, sofern nicht die Voraussetzung des § 1 Abs. 2
eingetreten ist.

* § 3

(1) Auf den Betrieb der Land- und Forstwirtschaft Binden die
Vorschriften des § 1 keine

Anwendung.

(2) Für ein land- oder forstwirtschaftliches Unternehmen, das nach Art
und Umfang einen in kaufmännischer Weise eingerichteten
Geschäftsbetrieb erfordert, gilt § 2 mit der Maßgabe, daß nach
Eintragung in das Handelsregister eine Löschung der Firma nur nach den
allgemeinen Vorschriften stattfindet, welche für die Löschung
kaufmännischer Firmen gelten.

(3) Ist mit dem Betrieb der Land- oder Forstwirtschaft ein Unternehmen
verbunden, das nur ein Nebengewerbe des land- oder forstwirtschaftlichen
Unternehmens darstellt, so Binden auf das im Nebengewerbe betriebene
Unternehmen die Vorschriften der Absätze 1 und 2 entsprechende
Anwendung.

* § 5

Ist eine Firma im Handelsregister eingetragen, so kann gegenüber
demjenigen, welcher sich auf die Eintragung beruft, nicht geltend
gemacht werden, daß das unter der Firma betriebene Gewerbe kein
Handelsgewerbe sei.

* § 6

(1) Die in betreff der Kaufleute gegebenen Vorschriften Binden auch auf
die Handelsgesellschaften Anwendung.

(2) Die Rechte und Pflichten eines Vereins, dem das Gesetz ohne
Rücksicht auf den Gegenstand des Unternehmens die Eigenschaft eines
Kaufmanns beilegt, bleiben unberührt, auch wenn die Voraussetzungen des
§ 1 Abs. 2 nicht vorliegen.

* § 59

1Wer in einem Handelsgewerbe zur Leistung kaufmännischer Dienste gegen
Entgelt angestellt ist (Handlungsgehilfe), hat, soweit nicht besondere
Vereinbarungen über die Art und den Umfang seiner Dienstleistungen oder
über die ihm zukommende Vergütung getroffen sind, die dem Ortsgebrauch
entsprechenden Dienste zu leisten sowie die dem Ortsgebrauch
entsprechende Vergütung zu beanspruchen. 2In Ermangelung eines
Ortsgebrauchs gelten die den Umständen nach angemessenen Leistungen als
vereinbart.

* § 60

(1) Der Handlungsgehilfe darf ohne Einwilligung des Prinzipals weder ein
Handelsgewerbe betreiben noch in dem Handelszweige des Prinzipals für
eigene oder fremde Rechnung Geschäfte machen.

(2) Die Einwilligung zum Betrieb eines Handelsgewerbes gilt als erteilt,
wenn dem Prinzipal bei der Anstellung des Gehilfen bekannt ist, daß er
das Gewerbe betreibt, und der Prinzipal die Aufgabe des Betriebs nicht
ausdrücklich vereinbart.

* § 74

(1) Eine Vereinbarung zwischen dem Prinzipal und dem Handlungsgehilfen,
die den Gehilfen für die Zeit nach Beendigung des Dienstverhältnisses
in seiner gewerblichen Tätigkeit beschränkt (Wettbewerbverbot), bedarf
der Schriftform und der Aushändigung einer vom Prinzipal
unterzeichneten, die vereinbarten Bestimmungen enthaltenden Urkunde an
den Gehilfen.

(2) Das Wettbewerbverbot ist nur verbindlich, wenn sich der Prinzipal
verpflichtet, für die Dauer des Verbots eine Entschädigung zu zahlen,
die für jedes Jahr des Verbots mindestens die Hälfte der von dem
Handlungsgehilfen zuletzt bezogenen vertragsmäßigen Leistungen
erreicht.

* § 84

(1) 1Handelsvertreter ist, wer als selbständiger Gewerbetreibender
ständig damit betraut ist, für einen anderen Unternehmer (Unternehmer)
Geschäfte zu vermitteln oder in dessen Namen abzuschließen.
2Selbständig ist, wer im wesentlichen frei seine Tätigkeit gestalten
und seine Arbeitszeit bestimmen kann.

(2) Wer, ohne selbständig im Sinne des Absatzes 1 zu sein, ständig
damit betraut ist, für einen Unternehmer Geschäfte zu vermitteln oder
in dessen Namen abzuschließen, gilt als Angestellter.

(3) Der Unternehmer kann auch ein Handelsvertreter sein.

(4) Die Vorschriften dieses Abschnittes Binden auch Anwendung, wenn das
Unternehmen des Handelsvertreters nach Art oder Umfang einen in
kaufmännischer Weise eingerichteten Geschäftsbetrieb nicht erfordert.

* _Viertes Buch Sozialgesetzbuch - Gemeinsame Vorschriften zur Sozialversicherung (SGB IV)_

* § 7 Beschäftigung

(1) 1 Beschäftigung ist die nichtselbständige Arbeit, insbesondere in
einem Arbeitsverhältnis.\\
2 Anhaltspunkte für eine Beschäftigung sind eine Tätigkeit nach
Weisungen und eine Eingliederung in die Arbeitsorganisation des
Weisungsgebers.

(1a) 1 Eine Beschäftigung besteht auch in Zeiten der Freistellung von
der Arbeitsleistung von mehr als einem Monat, wenn

1. während der Freistellung Arbeitsentgelt aus einem Wertguthaben nach
   § 7b fällig ist und

2. das monatlich fällige Arbeitsentgelt in der Zeit der Freistellung
   nicht unangemessen von

#+begin_quote
dem für die vorausgegangenen zwölf Kalendermonate abweicht, in denen
Arbeitsentgelt bezogen wurde.

#+end_quote

2 Satz 1 gilt entsprechend, wenn während einer bis zu dreimonatigen
Freistellung Arbeitsentgelt aus einer Vereinbarung zur flexiblen
Gestaltung der werktäglichen oder wöchentlichen Arbeitszeit oder dem
Ausgleich betrieblicher Produktions- und Arbeitszeitzyklen fällig ist.
3 Beginnt ein Beschäftigungsverhältnis mit einer Zeit der
Freistellung, gilt Satz 1 Nr. 2 mit der Maßgabe, dass das monatlich
fällige Arbeitsentgelt in der Zeit der Freistellung nicht unangemessen
von dem für die Zeit der Arbeitsleistung abweichen darf, mit der das
Arbeitsentgelt später erzielt werden soll.\\
4 EineBeschäftigung gegen Arbeitsentgelt besteht während der Zeit der
Freistellung auch, wenn die Arbeitsleistung, mit der das Arbeitsentgelt
später erzielt werden soll, wegen einer im Zeitpunkt der Vereinbarung
nicht vorhersehbaren vorzeitigen Beendigung des
Beschäftigungsverhältnisses nicht mehr erbracht werden kann. 5 Die
Vertragsparteien können beim Abschluss der Vereinbarung nur für den
Fall, dass Wertguthaben wegen der Beendigung der Beschäftigung auf
Grund verminderter Erwerbsfähigkeit, des Erreichens einer Altersgrenze,
zu der eine Rente wegen Alters beansprucht

Viertes Buch Sozialgesetzbuch-Gemeinsame Vorschriften für die
Sozialversicherung (SGB IV)

werden kann, oder des Todes des Beschäftigten nicht mehr für Zeiten
einer Freistellung von der Arbeitsleistung verwendet werden können,
einen anderen Verwendungszweck vereinbaren. 6 Die Sätze 1 bis 4 gelten
nicht für Beschäftigte, auf die Wertguthaben übertragen werden. 7Bis
zur Herstellung einheitlicher Einkommensverhältnisse im Inland werden
Wertguthaben, die durch Arbeitsleistung im Beitrittsgebiet erzielt
werden, getrennt erfasst; sind für die Beitrags- oder
Leistungsberechnung im Beitrittsgebiet und im übrigen Bundesgebiet
unterschiedliche Werte vorgeschrieben, sind die Werte maßgebend, die
für den Teil des Inlandes gelten, in dem das Wertguthaben erzielt
worden ist.

(1b) Die Möglichkeit eines Arbeitnehmers zur Vereinbarung flexibler
Arbeitszeiten gilt nicht als eine die Kündigung des
Arbeitsverhältnisses durch den Arbeitgeber begründende Tatsache im
Sinne des § 1 Abs. 2 Satz 1 des Kündigungsschutzgesetzes.

(2) Als Beschäftigung gilt auch der Erwerb beruBlicher Kenntnisse,
Fertigkeiten oder Erfahrungen im Rahmen betrieblicher Berufsbildung.

(3) 1 Eine Beschäftigung gegen Arbeitsentgelt gilt als fortbestehend,
solange das Beschäftigungsverhältnis ohne Anspruch auf Arbeitsentgelt
fortdauert, jedoch nicht länger als einen Monat. 2 Eine Beschäftigung
gilt auch als fortbestehend, wenn Arbeitsentgelt aus einem der Deutschen
Rentenversicherung Bund übertragenen Wertguthaben bezogen wird. 3 Satz
1 gilt nicht, wenn Krankengeld, Krankentagegeld, Verletztengeld,
Versorgungskrankengeld, Übergangsgeld, Pflegeunterstützungsgeld oder
Mutterschaftsgeld oder nach gesetzlichen Vorschriften Erziehungsgeld
oder Elterngeld bezogen oder Elternzeit in Anspruch genommen oder
Wehrdienst oder Zivildienst geleistet wird. 4Satz 1 gilt auch nicht für
die Freistellung nach § 3 des Pflegezeitgesetzes.

(4) Beschäftigt ein Arbeitgeber einen Ausländer ohne die nach § 284
Absatz 1 des Dritten Buches erforderliche Genehmigung oder ohne die nach
§ 4 Absatz 3 des Aufenthaltsgesetzes erforderliche Berechtigung zur
Erwerbstätigkeit, wird vermutet, dass ein Beschäftigungsverhältnis
gegen Arbeitsentgelt für den Zeitraum von drei Monaten bestanden hat.

* _Sechstes Buch Sozialgesetzbuch - Gesetzliche Rentenversicherung (SGB
VI)_

* § 2 Selbständig Tätige

1 Versicherungspflichtig sind selbständig tätige

1. Lehrer und Erzieher, die im Zusammenhang mit ihrer selbständigen
   Tätigkeit regelmäßig keinen versicherungspflichtigen Arbeitnehmer
   beschäftigen,

2. Pflegepersonen, die in der Kranken-, Wochen-, Säuglings- oder
   Kinderpflege tätig sind und im Zusammenhang mit ihrer selbständigen
   Tätigkeit regelmäßig keinen versicherungspflichtigen Arbeitnehmer
   beschäftigen,

3. Hebammen und Entbindungspfleger,

4. Seelotsen der Reviere im Sinne des Gesetzes über das Seelotswesen,

5. Künstler und Publizisten nach näherer Bestimmung des
   Künstlersozialversicherungsgesetzes,

6. Hausgewerbetreibende,

7. [@7] Küstenschiffer und Küstenfischer, die zur Besatzung ihres
   Fahrzeuges gehören oder als

#+begin_quote
Küstenfischer ohne Fahrzeug fischen und regelmäßig nicht mehr als vier
versicherungspflichtige Arbeitnehmer beschäftigen,

#+end_quote

8. [@8] Gewerbetreibende, die in die Handwerksrolle eingetragen sind und
   in ihrer Person die für die Eintragung in die Handwerksrolle
   erforderlichen Voraussetzungen erfüllen, wobei

#+begin_quote
Handwerksbetriebe im Sinne der §§ 2 und 3 der Handwerksordnung sowie
Betriebsfortführungen auf Grund von § 4 der Handwerksordnung außer
Betracht bleiben;ist

eine Personengesellschaft in die Handwerksrolle eingetragen, gilt als
Gewerbetreibender, wer als Gesellschafter in seiner Person die
Voraussetzungen für die Eintragung in die

Handwerksrolle erfüllt,

#+end_quote

9. [@9] Personen, die

   1. a)  im Zusammenhang mit ihrer selbständigen Tätigkeit
      regelmäßig keinen versicherungspflichtigen Arbeitnehmer
      beschäftigen und

   2. b)  auf Dauer und im Wesentlichen nur für einen Auftraggeber
      tätig sind; bei Gesellschaftern gelten als Auftraggeber die
      Auftraggeber der Gesellschaft.

2 Als Arbeitnehmer im Sinne des Satzes 1 Nr. 1, 2, 7 und 9 gelten

1. auch Personen, die berufliche Kenntnisse, Fertigkeiten oder
   Erfahrungen im Rahmen beruflicher Bildung erwerben,

2. nicht Personen, die geringfügig beschäftigt sind,

3. für Gesellschafter auch die Arbeitnehmer der Gesellschaft.
   

