#+title: Budget Friendly Foods
#+date: 2025-01-24T11:11:42+01:00
#+lastmod: 2025-01-24T11:11:42+01:00
# ISO 8601 date use output from
# C-u M-! date -Iseconds
#+draft: false
#+tags[]:

Source: https://www.myplate.gov/shopsimple/foods/all
# more

* Applesauce, unsweetened

** Tips
Unopened applesauce can be stored in the pantry for 12 – 18
months. Check the date on the label.

After opening, store in the refrigerator for 7-10 days.

To cut down on added sugars, look for “unsweetened” or “no sugar
added” on the label.

Large jars of applesauce can be more affordable than individual cups,
however cups can be a healthy snack choice on the go. Choose the
option that works best for your family.

** Serving ideas
Add applesauce to cooked hot cereals or baked goods.

Serve applesauce with pork and other meats instead of sauces that can be high in added sugars.

Serve applesauce over pancakes or waffles instead of syrup.

* Bananas
** Tips
Purchase green bananas now to use later in the week.

Did you know? Placing bananas in a brown paper bag will cause them to ripen quicker. Also, bananas can cause other fruits to ripen quicker if they are stored together.

Overripe bananas are delicious in yogurt, smoothies, oatmeal, or as an ingredient in whole wheat pancakes. Use now or peel and pop in the freezer for later.
** Serving ideas
Top your cereal, oatmeal, or yogurt with sliced bananas.

Make a fruit skewer with banana and other fruit cut into chunks.

Create a sandwich with wheat bread, banana slices, and your favorite nut butter.

Whip up banana “ice cream” for a tasty treat. Freeze ripe banana chunks and blend until smooth.

* Beets, canned
** Tips
Medium- and large-size beets are good for cooking; very large roots
are too woody for eating regardless of cooking method.

Look for smooth, hard, uniformly round beets that are free of cuts and
bruises.

Remove the beet greens and use immediately.
Store beets with their tops chopped off in individual plastic bags in
the coolest part of the refrigerator. These should last up to one week.

Once cooked, beets can be frozen with their peels removed.

Wash and scrub the beets before cooking. Beets peel best after
cooking, and they will stain many things they come into contact
with.  Wear gloves if you wish to avoid stained hands.

** Serving ideas
Tender beets can be eaten raw, but they are often cooked before eating
by boiling, steaming, or roasting.

Cooked beets can be sliced and served as a vegetable on one side of a plate.
* Black beans, canned
** Tips
Canned beans can be stored in the pantry for up to 5 years from the date of purchase. Check the date on the can.

Once opened, refrigerate beans and use within 4 days.

To cut down on sodium (salt), drain and rinse canned beans in a colander before using. Some stores may also carry low sodium (salt) products. Look for “‘less sodium” or “no salt added” on the label.

You may be able to save money by purchasing the store brand or larger cans of beans. Choose what works best for your family.
** Serving ideas
Add black beans to eggs and wrap in a tortilla with diced tomatoes and shredded cheddar cheese (reduced fat) for a delicious breakfast burrito.

Blend together black beans, salsa, lime juice, cumin, and cilantro to create a black bean dip. Serve with tortilla chips or raw vegetables.

“Beans and rice” or “rice and beans”... However you say it, black beans and rice make a great combo and a delicious and nutritious meal.

Make black beans patties mixed with diced bell pepper and your favorite herbs and spices.
* Blue cornmeal
** Tips
Blue cornmeal is a whole grain made from blue corn that has been dried and finely ground.

Blue cornmeal can be stored in an airtight container in a cool dark pantry for up to 6 months, or in the refrigerator for up to 1 year. 
** Serving ideas
Blue cornmeal can be used in muffins, cornbread, corn pone, rolls, and other baked goods. 

Combine blue cornmeal, flour, and your favorite seasonings to make a breading for chicken, pork, or fish.

Make a quick blue corn mush for breakfast or as a side dish by bringing 4 cups of water to a slow boil and adding 1/2 cup of blue cornmeal. Stir with a whisk until blended. Pour into a cup and add your favorite ingredients or seasonings.


* Blueberries, frozen, unsweetened
** Tips
Frozen blueberries can be stored in the freezer in an airtight container or freezer bag  for 10 - 18 months. Check the date on the package.

Look for blueberries that do not have sugar listed in the ingredients.

Frozen blueberries can be used in many ways without being thawed first, such as in smoothies, oatmeal, and yogurt. 

If you do need to thaw the blueberries, place only the amount you need in an airtight container to thaw  in the refrgerator.

Buy fresh blueberries when they are in season and offered at a lower cost and freeze the extra to use at a later date.
** Serving ideas
Create a quick and delicious smoothie by blending milk or fortified soy milk, frozen blueberries, and a banana. 

Add thawed frozen blueberries to your pancake or muffin batter or top oatmeal with thawed blueberries for more color and flavor at breakfast.

Mix thawed frozen blueberries with canned peaches and granola for a satisfying afternoon snack. 

* Bran flakes, ready-to-eat cereal
** Tips
Bran flakes (ready-to-eat cereal) can be stored unopened in the pantry for 6-12 months. Check the date on the box. 

Once opened, store in the pantry for 2-3 months.

Look for sales or store specials. If you are able to, buy an extra box when it’s on sale.

Many cereals are available as store or generic brands. If they work for your family, it may save you money. 
** Serving ideas
Mix bran flakes with dried fruit like raisins and your favorite nuts for a portable trail mix.

Add banana slices to your bran flakes cereal with milk for a hint of sweetness at breakfast.

Crush cereal into fine crumbs and add your favorite seasonings. Use the mixture instead of breadcrumbs when making baked breaded chicken, pork, or fish.


* Bread, whole wheat
** Tips
Bread can be stored in the pantry for about 5 days, or in the freezer for 3 months.

If bread is on sale, buy an extra loaf and freeze it. When you’re ready to use the frozen loaf, simply thaw at room temperature or pop a frozen slice in the toaster. 

On the label, look for “whole wheat” or “whole grain” as the first ingredient listed to choose a whole grain bread.
** Serving ideas
Top whole wheat toast with nut butter and fruit like sliced bananas or apples. 

Make your own whole grain croutons. Drizzle cubes of bread with oil and sprinkle with garlic and onion powder. Bake until toasted.

Try a new sandwich idea on wheat bread: roasted veggies and cheese, tofu and tomato, or hummus and turkey.

* Broccoli, frozen
** Tips
Frozen broccoli can be stored in the freezer for 10-18 months. 

You can often save money by purchasing larger bags of frozen broccoli. Thaw only what you need at a time. 

Frozen broccoli is typically available in 3 cuts: spears (stem plus floret), florets (just the top portion), and chopped (diced stems and florets). Choose the one that works best for your family’s taste and budget. 
** Serving ideas
Steam frozen broccoli on the stove until it is a rich, dark green color - usually 5-8 minutes. Add a dash of seasoning and enjoy!

Broccoli pasta: Add frozen broccoli to the pot of boiling pasta about three minutes before the end of the cooking time. Season as desired.

Roasted broccoli: Toss frozen broccoli with oil and a sprinkle of salt. Spread on a baking sheet and roast at 400 degrees F until browned.


* Brown rice
** Tips
Brown rice can be stored in the pantry for up to 1 year.

Once cooked, store in the refrigerator for 4 - 6 days.

Brown rice comes in various cooking varieties, including instant or regular. Regular-cook rice may be the least expensive option. Choose what works best for your family. 
** Serving ideas
Add cooked brown rice to vegetable soup for a quick meal. 

Create your own burrito bowl with brown rice, vegetables, your favorite protein food and top with shredded cheese or plain yogurt mixed with herbs and seasonings. 

Brown rice for breakfast? Yes! Warm it up with milk, raisins, and cinnamon or try your own creation.


* Buttermilk, low-fat
** Tips
Buttermilk should be refrigerated and must be used within 7-10 days after opening. Check the expiration date on the container. 

Buttermilk can be frozen for up to 3 months from the date of purchase.

Buttermilk is available in several varieties. Look for low-fat or fat free versions. 
** Serving ideas
Make a simple buttermilk dressing with lemon juice, olive oil, and herbs. Lightly drizzle on a garden salad packed with fresh vegetables.

Buttermilk works well in marinades because the slight acidity helps to tenderize meat. Mix with your favorite seasonings and try it for baked chicken or braised pork.

Buttermilk adds a rich creamy texture and tangy flavor to mashed potatoes. Try it in place of milk in your favorite mashed potato recipe.  


* Canned tuna, in water
** Tips
Canned tuna can be stored in the pantry for up to 3 years from the date of purchase.

Look for canned chunk light tuna, which is lower in methylmercury than albacore. 

You can often save money by purchasing the store brand, or by choosing larger cans or bundles of cans. 
** Serving ideas
Add canned tuna to a garden salad for an easy lunch.

Serve it with pasta. Make a tuna casserole or use it in a macaroni salad.

Combine canned tuna with plain Greek yogurt or mayonnaise and chopped celery. Spread the mixture onto whole wheat bread with sliced cucumbers for a portable sandwich.

* Cantaloupe
** Tips
Canned tuna can be stored in the pantry for up to 3 years from the date of purchase.

Look for canned chunk light tuna, which is lower in methylmercury than albacore. 

You can often save money by purchasing the store brand, or by choosing larger cans or bundles of cans. 
** Serving ideas
Thread cubes of cantaloupe and other favorite fruits on skewers. Serve with a yogurt dip.

Cantaloupe is a great sweet addition to a garden salad.

Try melon salsa! Combine diced cantaloupe with finely chopped red onion, cilantro, and a squeeze of lime juice for a zesty salsa that pairs well with seafood.



* Carrots
** Tips
Carrots are in season all year- in winter, spring, summer, and fall

Carrots can be stored in the refrigerator for 2 - 3 weeks from the date of purchase

Carrots are available fresh, frozen, or canned
** Serving ideas
Carrot sticks or baby carrots are a great portable snack. Pack them for work, activities, or when you travel.

Add diced or shredded carrots to your favorite soup, salad, or slaw.

Carrots are perfect for dipping! Try hummus, peanut butter, or a DIY dip made of yogurt mixed with herbs and spices.  


* Catfish, frozen
** Tips
Catfish is a white fish with a mild flavor that makes it easy to prepare in many different ways.

You may be able to save money by purchasing frozen fish. Look in the frozen seafood section of the store.

Thaw frozen fish in the refrigerator. It may take 1-2 days to thaw completely depending on the size of the fish.
** Serving ideas
Catfish fillets may be baked, broiled, or grilled.

Try catfish nuggets! Toss pieces of fish fillets in breadcrumbs or cornmeal and bake for lunch or dinner.

Make your own blackened catfish! Season with paprika and other spices, then cook on the stovetop. Serve along with brown rice and vegetables for a complete meal.

* Cheddar cheese, reduced fat
** Tips
Cheddar cheese can be stored in the fridge for 1 month. 

Cheddar cheese can be frozen for 3-4 months from the date of purchase. Once thawed, use within 3 days.

For shredded cheese, you may be able to save money by purchasing large bags or extra bags when it’s on sale. Store a reasonable amount for your family in an airtight container in the fridge, and freeze the rest of the package.
** Serving ideas
Try turkey on whole wheat bread with a slice of reduced fat cheddar cheese for an easy lunch option. 

Top whole wheat crackers with small slices of cheese and apple.

Make a quick breakfast sandwich with toasted whole wheat bread, cheese, and egg.

Sprinkle a bit of cheese on vegetables like steamed broccoli or brussels sprouts for extra flavor. 

* Chicken drumsticks or thighs
** Tips
Uncooked chicken should be refrigerated and can be stored for 1-2 days from the date of purchase. 

Once cooked, chicken should be refrigerated and used within 3-4 days or can be frozen and used within 2-6 months. 

When buying chicken, drumsticks and thighs are often less expensive than chicken breasts. Look for chicken breast when it is on sale.

If your store is having a sale on chicken, you can buy extra and freeze it uncooked for up to 9 months. 
** Serving ideas
Cook all poultry to minimal safe internal temperature of 165° F (74° C).

Use chicken to make soups and stews. Add canned tomatoes and different seasonings for endless variety.

Use cooked to top a salad, fill tacos, or in pasta sauce.

Sprinkle seasonings like garlic powder and pepper over chicken before grilling or broiling it.

* Collard greens
** Tips
Collard greens are in season in spring, winter, and fall. Fruits and vegetables may cost less when they are in season. 

Choose bunches with dark green leaves with no yellowing.

From the date of purchase, fresh collard greens can be stored in the refrigerator for up to 4 days. 

You may be able to save money by purchasing and chopping bunches of collard greens instead of buying pre-cut bags.

** Serving ideas
Need a quick side dish? Mix collard greens with chicken broth, onions, and paprika in a saucepan. Let greens simmer on low heat until ready to serve.

Top any bowl of soup with a handful of collards and let the heat of the soup quick steam the greens for an added nutritional boost. 

Add chopped collard greens to the pasta pot when pasta is about 5 minutes from being done. Season with a small amount of olive oil and your favorite herbs and spices.

Collard greens are a great addition to any stir fry. Try them with garlic, onion, honey, and chicken breast or tofu.

* Corn tortillas
** Tips
Corn tortillas can be stored in the pantry for up to 1 month or in the refrigerator for up to 2 months.

Corn tortillas can also be frozen for up to 6 months in a sealed container.

You may be able to save money by purchasing corn tortillas in large quantities. Store only what you can use soon in the pantry or refrigerator and freeze the rest.

Frozen tortillas can be thawed easily in the fridge overnight.
** Serving ideas
Make your own tortilla strips to add crunch to soups, salads, or taco bowls. Brush both sides of the tortilla with oil, then cut into strips with a knife or pizza cutter. Bake at 350 degrees F until lightly browned, about 5-10 minutes.

Create a quick and tasty tostada! Bake tortillas in a single layer at 400 degrees F for about 6 minutes, flipping halfway through. Add your favorite toppings like diced onions, black beans, and salsa.

Ever tried “migas” for breakfast? You can make migas by sautéeing strips of corn tortillas in olive oil until just crispy. Then, add diced onion, bell pepper, and whipped eggs and stir until cooked through.

* Corn, canned
** Tips
Unopened canned corn can be stored in the pantry for 2-5 years from the date of purchase. After opening, store in the refrigerator for 3-4 days.

Did you know? Canned corn is fully cooked, so it is safe to eat without further cooking.

Canned vegetables are great to keep on hand. Look for “low sodium” or “no salt added” on the label, or rinse canned vegetables to reduce their sodium (salt) content.
** Serving ideas
Sauté canned corn in a small amount of oil with green chilies, tomato, and onions for a colorful side dish.

Create a quick pasta salad with canned corn, chopped vegetables, beans and vinaigrette.

Add corn to soup, chili, salsa, chowder, tacos, burrito bowls.

Combine corn with lima beans to make succotash.


* Cornmeal
** Tips
Cornmeal can be stored in an airtight container in a cool dark pantry for up to 6 months, or in the refrigerator for up to 1 year. 

Cornmeal is made from dried corn; it can be either yellow or white.
** Serving ideas
Cornmeal is a versatile baking ingredient. Use it in muffins, scones, biscuits, cookies, and cakes.

Use cornmeal to make crispy baked okra bites. Mix cornmeal with paprika and garlic powder. Roll okra pieces in the mixture, then bake at 400 degrees F for 25 minutes.

Combine cornmeal, flour, and your favorite seasonings to make a breading for chicken, pork, or fish.

Try cornmeal as a hot breakfast cereal! Combine 1 cup of water, 1 cup of cornmeal, and a pinch of salt. Slowly pour the mixture into 3 cups of boiling water, stirring constantly. Cook until thickened, then serve with syrup.


* Cottage cheese, low-fat
** Tips
Cottage cheese can be stored in the fridge for 2 weeks (unopened) or 1 week (opened).

Look for low-fat or fat-free varieties. 

If you consume cottage cheese often, you may be able to save money by purchasing large tubs instead of small or individual containers. Choose what works best for your family. 
** Serving ideas
Spread cottage cheese on whole wheat crackers and top with your favorite veggies.

Top cottage cheese with canned peaches, mandarin oranges or sliced bananas.

Add a spoonful of cottage cheese to scrambled eggs or pasta dishes for added flavor and protein.

* Couscous
** Tips
Couscous can be stored in the pantry for up to 1 year.

Once cooked, store in the refrigerator for 4-6 days.

Couscous is a tiny pasta that comes in different varieties. Most of the couscous you will find in stores is "instant" or quick-cooking.

Some stores may carry whole wheat couscous.
** Serving ideas
The couscous found in most stores can be prepared quickly by mixing with boiling water and covering for 5 minutes, then fluffing with a fork before serving. Follow the directions on the label.

Couscous has a mild taste that makes it easy to use in a variety of ways. If you want to keep it simple, try it with a drizzle of olive oil and a pinch of salt.

For a savory side dish, cook couscous in vegetable broth and add thawed frozen peas and carrots.

Go for a sweet treat by mixing raisins and your favorite nuts into cooked couscous.

* Cucumbers
** Tips
Cucumbers are in season in summer. Fruits and vegetables may cost less when they are in season. 

From the date of purchase, cucumbers can be stored in the refrigerator for 4-6 days. 

Choose firm cucumbers with a dark green color. 

Did you know that there are nutrients and fiber found in the dark green skin of a cucumber? So, skip the peeling step and eat the cucumber with the skin – but don’t forget to wash well.

** Serving ideas
Slice up a cucumber, then drizzle with lime juice and sprinkle with chili powder.

Mix finely diced, peeled and seeded cucumber into chicken, shrimp or tuna salad.

Add cucumber slices to your favorite sandwich or wrap for added crunch. 

Make cucumber canoes for a fun snack. Slice cucumbers in half lengthwise and scoop the seeds out with a spoon. Fill with cottage cheese and diced tomatoes. 

Pair cucumbers with hummus for a filling and delicious snack. 

* Dairy milk, low-fat or fat-free (or lactose-free or fortified soy versions)
** Tips
Milk should be refrigerated and must be used within 7 days after opening. Check the expiration date on the container. 

Milk can be frozen for up to 3 months from the date of purchase.

If milk is on sale, buy a second container. Pour out a small amount to
allow the liquid to expand, and freeze the container. Thaw in the
fridge overnight, shake well, and use within 3 days.
** Serving ideas
Cook hot cereals like oatmeal or grits in milk to give it a creamy texture.

Drink milk with meals for a refreshing beverage.

Make or order your tea or coffee with milk.

* Eggs
** Tips
Store-bought eggs should be stored in the refrigerator and can be used for 3-5 weeks from the date of purchase. Check the expiration date on the carton. 

Open the carton and check for cracked eggs before purchasing.

You can often save money by purchasing larger cartons of eggs.
** Serving ideas
Scramble eggs with peppers, onions and salsa. Serve as is or roll in a whole wheat tortilla for a portable meal.

Hard cooked eggs make a great snack, or can be added to a salad for protein. Boil several at once and store in the refrigerator.

Eggs are a versatile protein food that can be included in baked dishes, sandwiches, omelets, or scrambled into rice and noodle dishes.  

* Evaporated milk, fat free
** Tips
Evaporated milk can be stored in the pantry for 1 year. 

Once opened, refrigerate and use within 4-5 days.

Evaporated milk is sold in a can and is often found in your store's baking aisle.
** Serving ideas
Add evaporated milk to soups, pasta dishes, and dressings for creamy texture. 

Stir evaporated milk in coffee, tea, or smoothies for added richness.

Use evaporated milk to thicken sauces and smoothies.


* Flour tortillas
** Tips
Flour tortillas can be stored in the pantry or refrigerator for up to 3 months.

Flour tortillas can also be frozen for up to 6 months in a sealed container.

You may be able to save money by purchasing flour tortillas in large quantities. Store only what you can use soon in the pantry or refrigerator and freeze the rest.

Frozen tortillas can be thawed easily in the fridge overnight.

Some stores may carry whole wheat tortillas.

** Serving ideas
Flour tortillas have a mild flavor and can easily be used in either sweet or savory dishes.

Spread peanut butter on a flour tortilla and place banana slices in the center. Roll up for an easy on the go snack. 

Make a quick veggie wrap! Spread hummus onto a tortilla and top with thinly sliced cucumber and carrot slices. Roll up and enjoy.

Make some mini pizzas for an afterschool snack or quick dinner! Brush tortillas with olive oil and bake at 400 degrees F until golden. Remove from the oven and top with tomato sauce, veggies, and mozzarella cheese. Bake again until cheese is melted. Slice into wedges and enjoy!

* Grapefruit
** Tips
Grapefruit is in season in winter. 

From the date of purchase, grapefruit can be stored at room temperature for up to 10 days, or up to 3 weeks in the refrigerator.

To choose ripe grapefruit, look for a deeper color and fruit that will give a little if you squeeze it.  The firmer the grapefruit feels, the less ripe it will be.

Did you know? Grapefruit got its name because of the way it grows on trees: clustered like a bunch of grapes. 

Grapefruit can interact with some common medications. Check with your doctor to see if it’s a safe choice for you.

** Serving ideas
Grapefruit makes a great snack all on its own. Cut into slices, or scoop out the sections. If you want to season it, try a light sprinkle of cinnamon or even black pepper!

Grapefruit adds extra flavor and color to salads. Top a lettuce of your choice with peeled and diced grapefruit, chickpeas, and a small amount of vinaigrette for a refreshing meal. 

Brush grapefruit slices with olive oil, then grill or broil the slices to serve with cooked chicken or fish. 

* Greek yogurt, plain, nonfat
** Tips
Greek yogurt should be refrigerated and can be stored for 1-2 weeks from the date of purchase. Check the expiration date on the package. 

Freezing Greek yogurt is not recommended.

You can often save money by purchasing larger tubs of Greek yogurt instead of individual containers. Choose what works best for your family.
** Serving ideas
Use plain Greek yogurt to top tacos, pitas, chili, potatoes, and more. 

Try Greek yogurt in your favorite tuna salad or pasta salad recipes for added calcium, tangy flavor, and creamy texture. Use plain Greek yogurt to make a variety of deliciously smooth dips, spreads, and salad dressings. 

Add canned peaches, pears, or pineapple to your Greek yogurt for a healthy snack.


* Green (string) beans
** Tips
Green beans are in season in summer and fall. Fruits and vegetables may cost less when they are in season.

Green beans can be stored in the refrigerator for up to 5 days from the date of purchase.

Green beans are available fresh, frozen, and canned. 
** Serving ideas
Sauté green beans in a pan with olive oil and a splash of lemon juice for an easy side.

Trim off the ends and steam green beans until tender, then toss with your favorite vinaigrette.

Stir frozen green beans into your favorite soup or stew to boost the amount of vegetables.


* Green cabbage
** Tips
Cabbage is in season in winter, spring, and fall.

From the date of purchase, cabbage can be stored in the refrigerator for 1-2 weeks.

You can save money by purchasing and chopping heads of cabbage instead of buying pre-cut bags. 
** Serving ideas
Make a quick slaw with shredded cabbage, oil, vinegar, and spices.

Sauté shredded cabbage with onions and your favorite seasoning until soft and tender for a delicious side dish.

Add extra crunch to your salads, soups, tacos, or sandwiches by topping them off with thinly sliced cabbage.


* Hominy, canned
** Tips
Did you know? Hominy is made from dried maize (corn) kernels.

Unopened canned hominy can be stored in the pantry for 1-2 years. Check the date on the can.   After opening, store in the refrigerator for 3-4 days.

Canned vegetables are great to keep on hand. Look for “low sodium” or “no salt added” on the label. Rinse canned vegetables to reduce their sodium (salt) content.
** Serving ideas
Canned hominy is fully cooked, so it is safe to eat without further cooking.

Use hominy like you would use canned beans in a soup, stew, or casserole. Unlike many beans, hominy won’t absorb the flavor of whatever you’re cooking with and will keep its own delicious flavor.

Canned veggies like hominy are a great shortcut in the kitchen. Keep them on hand to add more flavor, color, and nutrients to any meal no matter the season.


* Kidney beans, canned
** Tips
Canned beans can be stored in the pantry for up to 5 years from the date of purchase. Check the date on the can.

Once opened, refrigerate beans and use within 4 days.

To cut down on sodium (salt), drain and rinse canned beans in a colander before using. Some stores may also carry low sodium (salt) products. Look for “‘less sodium” or “no salt added” on the label.

You may be able to save money by purchasing the store brand or larger cans of beans. Choose what works best for your family.

** Serving ideas
Add kidney beans to your favorite pasta sauce and spoon over whole wheat spaghetti. Serve with a garden salad or steamed veggies for a complete meal.

For a quick and easy side, stir together canned corn, kidney beans (drained and rinsed), and chili powder.

Kidney beans make a great addition to chili. Whether you prefer chili con carne or vegetarian chili, stir in kidney beans for added fiber and flavor.

Adding kidney beans to a meal can be a quick way to add protein. Mix beans with some pico de gallo (or salsa) and greens for a quick taco salad.

* Lentils
** Tips
Lentils can be stored in the pantry for up to 1 year from the date of purchase.

After cooking, store lentils in the refrigerator for up to 5 days.

Lentils are available in most food stores in the dried and canned bean section.

Unlike dry beans, dry lentils do not have to be pre-soaked and are quick to cook. Rinse dry lentils before cooking.
** Serving ideas
Basic cooking directions: combine 1 cup of rinsed dry brown lentils with 3 cups of water. Bring to a boil, then simmer on low heat for 30 minutes or until tender.

Lentils can be added to or substitute for meat in chili, tacos, sauces, and meatloaf.

Combine lentils with rice, vegetables, or pasta to create a meal.



* Mangos
** Tips
Mangos are in season in summer and fall. 

From the date of purchase, mangoes can be stored at room temperature for up to 5 days, or up to 1 week in the refrigerator.

To choose a ripe mango, focus on feel- not color. Pick one up and give it a gentle squeeze. A ripe mango will give slightly, while an unripe mango will be hard. 

You can plan ahead and choose less ripe mangos when shopping; simply put them in a paper bag when you get home and wait for them to ripen.
** Serving ideas
Create a mango salsa with diced mango, red onions, cilantro, lime juice, and jalapenos (optional) or red peppers. Serve over fish, chicken or pork.

For a frozen treat, blend sliced mangos and orange juice. Freeze in ice cube trays with a popsicle stick or straw. 

Make a mango smoothie: blend 1 cup of orange juice, ½ cup of low-fat yogurt and one banana. Add 6 ice cubes and 1 diced mango. Blend again. 

For a new twist on a classic sandwich, toast whole wheat bread, spread with peanut butter, and add mango slices.


* Oatmeal, regular or quick
** Tips
Dry oatmeal can be stored in the pantry for up to 12 months.

You can often save money by purchasing oatmeal canisters instead of individual packets. 

To cut down on added sugars, look for plain oatmeal and add your own flavorings at home. 
** Serving ideas
Oatmeal isn’t just for breakfast! Serve as a side dish or mix in ingredients for a one-dish meal. 

Make it sweet: Mix in fruit (fresh, dried, or thawed frozen), cinnamon, crushed nuts or your favorite nut butter. 

Make it savory: Try cooking with egg, green onions, and a sprinkle of shredded cheese on top.

Oatmeal can replace breadcrumbs in some recipes like meatloaf.

* Okra, frozen
** Tips
Frozen okra can be stored in the freezer for 10-18 months.

You can often save money by purchasing larger bags of frozen okra. Thaw only what you need at a time. 

To thaw frozen okra, place the amount you will need in the refrigerator overnight or thaw in a colander under running water. If you are boiling, steaming, or sauteeing – you do not need to thaw the okra first. 

Frozen okra is available whole or cut. Choose the one that works best for your family’s taste.

** Serving ideas
Okra can be cooked quickly and easily by either steaming or boiling for 8-10 minutes. Drain and season with turmeric and cayenne pepper, or your favorite herbs and spices.

Okra can also be sautéed! Prepare with vinegar or other acidic ingredients like tomatoes for the best texture.

Crispy okra bites make a great snack or side. Mix cornmeal with paprika and garlic powder. Roll thawed okra pieces in the mixture, then bake at 400 degrees F for 25 minutes.

Okra tastes great in curries, sautés, and soups. It is traditionally used in Gumbo to help thicken the soup.

* Oranges
** Tips
Oranges are in season in winter. 

From the date of purchase, oranges can be stored at room temperature for up to a week, and up to 3 weeks in the refrigerator.

You can often save money by buying a bag of oranges, rather than purchasing them individually. 

** Serving ideas
Keep it simple- orange slices are delicious on their own. Serve some up for a  sweet snack after school or work.

Top a salad with orange chunks for added flavor.

Add orange slices to your water pitcher for a refreshing drink.

* Pasta, whole wheat
** Tips
Uncooked dry pasta can be stored in the pantry for up to 1 year.

Once cooked, store in the refrigerator for 3 - 5 days.

On the label, look for “whole grain” or “whole wheat” flour.

You may be able to save money by purchasing the store brand. 

** Serving ideas
When boiling pasta, add frozen veggies during the last 5 minutes for a colorful one pot dish. 

Mix cooked spaghetti with canned tuna, vegetables, oil, and seasonings for a quick meal.

Make an easy white bean and pasta dish: combine cooked pasta, drained/rinsed cannellini beans, canned diced tomatoes, canned corn, and oil. Season as you like. 

* Peaches, canned
** Tips
Unopened canned peaches can be stored in the pantry for 12-18 months. Check the date on the label. 

After opening, store in the refrigerator for 5-7 days.

To cut down on added sugars, look for peaches canned in 100% juice or water, rather than syrups.

Cans of peaches can be more affordable than individual cups, however cups can be a healthy snack choice on the go. Choose the option that works best for your family.
** Serving ideas
Canned peach slices are a great addition to hot or cold cereals, pancakes, waffles, and low-fat yogurt or cottage cheese.

Add diced canned peaches to your instant oatmeal for a quick and tasty breakfast.

Peaches taste great warm! Drain peach halves and sprinkle with cinnamon. Broil in your oven for 5-10 minutes until light brown.

Toss canned peaches into a blender with low-fat yogurt, bananas, and ice; then blend for a delicious smoothie.


* Peanut butter
** Tips
Unopened peanut butter can often be stored in the pantry for up to 2 years. Check the date on the label.

Once opened, peanut butter can be stored in the pantry for 2 months. If the peanut butter is labeled as natural, store it in the fridge for up to 4 months.

You can often save money by purchasing the store brand of peanut butter and by purchasing a larger container.  
** Serving ideas
Peanut butter makes a great dip for crunchy fruits and vegetables like apple and pear slices or sticks of carrot and celery.

Make mini sandwiches of peanut butter and whole wheat crackers for an easy snack on the go.

Use peanut butter to make a peanut sauce to go with noodles.


* Peanuts
** Tips
Unopened peanuts can be stored in the pantry until the use-by date on the package.

Once opened, peanuts can be stored in the pantry for up to 2 weeks or in the refrigerator for up to 4 weeks.

To reduce sodium (salt), look for dry roasted, unsalted peanuts. 

You may be able to save money by buying large containers of peanuts. Purchase only what you know you can use within the timeframes above.
** Serving ideas
Mix peanuts, dried fruit (like raisins), and toasted oat cereal for an easy and portable trail mix.

Leave peanuts in large pieces or crush to use as a topping for soups, stews, and salads.

Add a protein-filled crunch to stir-fried vegetables by mixing in peanuts. Serve over brown rice or whole wheat noodles.

Add some crunch to your yogurt parfait by adding crushed peanuts.

* Pears, canned
** Tips
Unopened canned pears can be stored in the pantry for 12-18 months. Check the date on the label. 

After opening, store in the refrigerator for 5-7 days.

To cut down on added sugars, look for pears canned in 100% juice or water, rather than syrups.

Cans of pears can be more affordable than individual cups, however cups can be a healthy snack choice on the go. Choose the option that works best for your family.
** Serving ideas
Use diced canned pears as a topping for whole wheat waffles, oatmeal, or yogurt.

Top yogurt or cottage cheese with canned diced pears for an easy snack. 

Combine canned pears with lemon juice and cinnamon to cook down into a quick and easy pear butter.

* Pineapple, canned
** Tips
Unopened canned pineapple can be stored in the pantry for 12-18 months. Check the date on the label.

After opening, store in the refrigerator for 5-7 days.

To cut down on added sugars, look for pineapple canned in 100% juice or water, rather than syrups.
** Serving ideas
Top yogurt or cottage cheese with canned pineapple for a snack.

Make your own pineapple sorbet! Freeze canned chunks, then blend until smooth.

Top your chicken sandwich or burger with a canned pineapple ring for a great sweet-savory combination.

* Pinto beans, canned
** Tips
Canned beans can be stored in the pantry for up to 5 years from the date of purchase. Check the date on the can.

Once opened, refrigerate beans and use within 4 days.

To cut down on sodium (salt), drain and rinse canned beans in a colander before using. Some stores may also carry low sodium (salt) products. Look for “‘less sodium” or “no salt added” on the label.

You may be able to save money by purchasing the store brand or larger cans of beans. Choose what works best for your family.
** Serving ideas
Mash 1 can of pinto beans (drained and rinsed) with chili powder and garlic powder to taste. Spread on celery sticks and top with salsa for a crunchy snack.

Make an easy three bean salad. Combine 1 can each of pinto beans, green beans, kidney beans,  with diced onions and tomatoes with your favorite vinaigrette.

Add pinto beans to soups, stews, chilis or even pasta salads for added flavor and texture.

* Plain yogurt, low-fat
** Tips
Yogurt should be refrigerated and can be stored for 1-2 weeks from the date of purchase. Check the expiration date on the package.

Yogurt can be frozen for 1-2 months from the date of purchase.

Yogurt can be frozen in its original container. When you’re ready to use it, just thaw in the fridge overnight, mix well, and serve within 3 days.

You can often save money by purchasing larger tubs of yogurt instead of individual containers or tubes. Choose what works best for your family.
** Serving ideas
Use plain yogurt to top tacos, pitas, chili, potatoes, and more. 

Prep fruit and yogurt smoothies for after school or work. 

Make a homemade dip with plain yogurt and your favorite herbs and spices. 

Make your own tzatziki sauce with plain yogurt, grated cucumber (squeezed dry), lemon juice, oil, garlic and spices.


* Popcorn, air-popped
** Tips
Dry popcorn kernels can be stored in the pantry for up to 1 year after opening. 

Purchasing popcorn kernels instead of microwave ready popcorn bags is often less expensive, and is lower in salt (sodium).

You don’t need special equipment to air pop popcorn kernels. Look online for a microwave or stovetop recipe that works for you.
** Serving ideas
You don’t need special equipment to air pop popcorn kernels. Look online for a microwave or stovetop recipe that works for you.

Make a trail mix by combing popcorn with dried fruit, nuts, and seeds. 

Toss popcorn in oil and add a little garlic powder and pepper.

For a sweet treat, toss popcorn in oil and sprinkle with a dash of cinnamon. 


* Potatoes
** Tips
Potatoes are in season in fall and winter but can be purchased all year round. 

Potatoes can be stored 1-2 months in the pantry, from the date of purchase. 

Potatoes are available fresh, frozen, and canned.

You can often save money by buying a bag of potatoes, rather than buying them individually. 
** Serving ideas
Microwaved: Clean the potato and prick several times with a fork. Microwave on a plate for 10 minutes, turning over halfway through cooking. Season and enjoy!

Oven roasted: Clean and cut potatoes into 1 inch cubes. Toss in a bowl with oil and your favorite spices. Bake at 450 degrees F for 30 minutes.

Boiled: Clean and cut potatoes into 1 inch cubes. Boil until you can easily pierce with a fork. Mix with a bit of unsalted tub margarine and seasonings. 


* Raisins
** Tips
Unopened raisins can be stored in the pantry or refrigerator for up to 6 months. Check the date on the label.

After opening, store in the pantry or refrigerator for up to 1 month.

Canisters of raisins can be more affortable than invididual small boxes, however boxes can be a healthy snack choice on the go. Choose the option that works best for your family.

Dried fruit like raisins can be a choking hazard for young children. For more information, see: Reducing the Risk of Choking in Young Children at Mealtimes
** Serving ideas
Dried fruit like raisins can be a great way to take fruit on the go. Pack some on its own or mixed with toasted oat cereal for a quick snack.

Top off your oatmeal with a handful of raisins and a sprinkle of cinnamon for an easy weekday breakfast.

Making chicken or tuna salad? Raisins are a tasty addition to any salad and add the right amount of sweetness and texture.


* Ricotta cheese, part skim
** Tips
Ricotta cheese can be stored in the fridge for 2 weeks (unopened) or 1 week (opened).

Freezing ricotta cheese is not recommended.

Look for varieties made with part skim milk. 

If you eat ricotta cheese often, you may be able to save money by purchasing large tubs instead of small containers. Choose what works best for your family.
** Serving ideas
Add a little ricotta cheese to your whole wheat pancake batter for extra fluffy pancakes.

Top whole wheat toast with ricotta and an egg or your favorite canned fruit.

Make a quick dip with ricotta cheese, a drizzle of olive oil, and your favorite seasonings. Serve with whole wheat crackers for an easy snack. 

For a sweet treat, combine ricotta cheese with fruit, crunchy granola, and honey. 


* Salmon, frozen
** Tips
Salmon is a flaky fish with flesh ranging from orange to dark red in color. 

Salmon is a source of omega-3 fatty acids which, as part of a healthy diet, may help reduce the risk of heart disease.

You may be able to save money by purchasing frozen fish. Look in the frozen seafood section of the store.

Thaw frozen fish in the refrigerator. It may take 1-2 days to thaw completely depending on the size of the fish.

** Serving ideas
Salmon fillets can be baked, broiled, or grilled.

Season salmon filets with lemon juice and your favorite seasonings. Heat olive oil in a pan and sear salmon on each side until the internal temperature reaches 145°F.

Place salmon filets skin side down on foil. Top with a drizzle of oil, onion slices, and lemon pepper or other seasonings. Bake at 350°F for 15-20 minutes, or until the fish reaches 145°F.
* Strawberries, frozen, unsweetened
** Tips
Frozen strawberries can be stored in the freezer for 10 - 18 months. Check the date on the package.

To cut down on added sugars, check the ingredients list. Look for strawberries that do not have sugar listed in the ingredients.

Frozen strawberries can be used in many ways without being thawed first, such as in smoothies. 

If you do need to thaw some, place only the amount you need in an airtight container to thaw slowly in the refrgerator. 
** Serving ideas
Make a parfait! Layer low-fat plain yogurt, whole grain granola, and thawed frozen strawberries.

Blend milk or fortified soy milk, frozen strawberries, and a banana for a quick and delicious smoothie.

Add frozen strawberries to a pot with a splash of lemon juice and a sprinkle of sugar. Simmer until tender, and use as a syrup on whole wheat pancakes or French toast. 

Make a strawberry vinaigrette! Thaw and combine 1 cup diced frozen strawberries, 2 tbsp apple cider vinegar, 2 tbsp olive oil, and salt and pepper to taste. Use as a salad dressing or as a marinade for chicken or pork.

* Summer squash (crookneck, pattypan, zucchini)
** Tips
Summer squash is in season in summer. Fruits and vegetables may cost less when they are in season.

Choose firm squash with no wrinkled skin or soft spots.

Summer squash can be stored up to 2 days at room temperature, and up to 5 days in the refrigerator. Wash just before using. 

There are many types of summer squash, including chayote, cousa, crookneck, pattypan, and zucchini.
** Serving ideas
Add steamed summer squash to your favorite pasta sauce and serve over spaghetti for an easy weeknight meal. 

Use a vegetable peeler to create thin shavings of raw zucchini or crookneck squash that can add crunch to salads or sandwiches.

Sauté sliced summer squash in olive oil and your favorite seasonings for a quick side dish. 

* Walleye, frozen
** Tips
Walleye is a flaky, mild-flavored white fish that can be prepared in many ways.

You may be able to save money by purchasing frozen fish. Look in the frozen seafood section of the store.

Thaw frozen fish in the refrigerator. It may take 1-2 days to thaw completely depending on the size of the fish.

** Serving ideas
Walleye can be baked or broiled in the oven, pan-seared on the stove top, or grilled.

Season baked walleye fillets with herbs like dill, basil, or parsley and serve with a squeeze of fresh lemon juice. 

Use walleye in your favorite soup, chowder, or jambalaya recipe. 

* Watermelon
** Tips
Watermelon is in season in summer. Fruits and vegetables may cost less when they are in season.

To choose a ripe watermelon, check the field spot (the lighter part of the melon that rested on the ground during growth). If the field spot is yellow or cream colored, it’s ripe!

You may be able to save money by purchasing and cutting a whole melon instead of buying containers of pre-sliced watermelon. Choose the option that works best for your family.

Before cutting, scrub the outer surface of the melon thoroughly with cool tap water.

Store whole watermelon at room temperature until ripe, for up to 2 weeks.

Refrigerate cut watermelon in an airtight container for use within 5 days.

** Serving ideas
Watermelon slices are a refreshing summer treat! For something different, use cookie cutters to create fun shapes.

For DIY flavored water, toss frozen watermelon cubes into your pitcher for a refreshing drink.

Blend watermelon cubes, Greek yogurt, and a banana together for a refreshing smoothie.

* White fish (haddock, tilapia, whiting)
** Tips
White fish varieties often have a mild flavor that make them easy to prepare in many different ways. Choose fish varieties that are lower in methylmercury, such as catfish, flounder/flatfish, haddock, hake, mullet, pollock, tilapia, and whiting.

Fresh fish can be stored in the refrigerator for up to 3 days from the date of purchase, or up to 6 months in the freezer.

You may be able to save money by purchasing frozen fish. Look in the frozen seafood section of the store.

Thaw frozen fish in the refrigerator. It may take 1-2 days to thaw completely depending on the size of the fish.

** Serving ideas
Toss fish fillets in breadcrumbs and bake for lunch or dinner.

Make fish tacos for a delicious and fun meal. Top with diced tomatoes, onions and a splash of lime juice. 

Pan seared fish can be a quick and easy weeknight dinner. Sprinkle your favorite seasonings on both sides of the fish and cook in a small amount of olive oil until it reaches an internal temperature of 145°F.

* Wild rice
** Tips
Wild rice has long, black whole grains with a nutty flavor and can be used in many ways.

Wild rice can be stored in the pantry for up to 1 year.

Once cooked, store in the refrigerator for 4 - 6 days.

** Serving ideas
Wild rice can be cooked and eaten on its own, or can be used in soups, casseroles, stuffing, or pilafs.

Add cooked wild rice to chicken or vegetable soup for a quick meal. 

Create your own rice bowl with cooked wild rice, your favorite vegetables, and a sprinkle of cheese. 

* Winter squash (acorn, butternut, hubbard, kabocha)
** Tips
Winter squash is in season in fall and winter, but some varieties can be purchased all year round.

Winter squash can be stored up to 6 weeks in the pantry, and up to 3 months in the refrigerator.

There are many types of winter squash, including acorn, butternut, buttercup, calabaza, carnival, delicata, hubbard, kabocha, and spaghetti.

** Serving ideas
Steaming is the quickest way to cook winter squash. Peel, seed, and cut squash into chunks. Steam until tender, about 20 minutes.

For a sweet treat, cut butternut or acorn squash into sections and remove the seeds. Drizzle with olive oil, honey, and cinnamon. Bake at 350 degrees F for 45 minutes or until soft.

Ever try butternut squash oven fries? Peel, seed, and cut squash into strips. Toss with olive oil, salt, pepper, and Cajun seasoning. Bake on a cooking sheet at 450 degrees F for 15-20 minutes, turning once.

Once spaghetti squash is cooked, the flesh inside is long and stringy like spaghetti. Use a fork to pull out the strands and top with your favorite pasta sauce for an easy dish.

