#+title: 实惠健康的未加工食品
#+date: 2025-01-24T11:11:42+01:00
#+lastmod: 2025-01-24T11:11:42+01:00
# ISO 8601 date use output from
# C-u M-! date -Iseconds
#+draft: false
#+tags[]:

本文介绍了可广泛获得的未加工或微量加工食品，包括其储存、季节性和烹饪方
法。

Source: https://www.myplate.gov/shopsimple/foods/all
# more

* 钠摄入量
https://medlineplus.gov/ency/article/002415.htm

健康成人的钠摄入量应限制在每天 2,300 毫克。患有高血压的成年人每天的钠
摄入量不应超过 1,500 毫克。患有充血性心力衰竭、肝硬化和肾病的人可能需
要更少的钠。

饮食中的钠（称为膳食钠）以毫克（mg）为单位。食盐的钠含量为 40%。一茶匙
（5 毫升）食盐含有 2,300 毫克钠。

钠天然存在于大多数食物中。钠的最常见形式是氯化钠，也就是食盐。牛奶、甜
菜和芹菜中也天然含有钠。饮用水中也含有钠，但含量取决于水源。钠还添加到
许多食品中。这些添加物包括谷氨酸钠（味精）、亚硝酸钠、糖精钠、小苏打
（碳酸氢钠）和苯甲酸钠。喼汁、酱油、洋葱盐、大蒜盐和肉汤块中都含有这些
物质。

熏肉、香肠和火腿等加工肉类以及罐装汤和蔬菜也含有添加钠。包装饼干、点心
蛋糕和甜甜圈等加工烘焙食品通常也含有较高的钠。快餐食品的钠含量通常很高。

饮食中钠含量过高可能导致 某些人会患高血压，患有心力衰竭、肝硬化或肾病
的人会严重积水。

* 水果和果汁
** 苹果酱，无糖，添加维生素 C
未开封的苹果酱可在储藏室中存放 12 - 18 个月。请查看标签上的日期。开封
后，可在冰箱中存放 7-10 天。为减少添加糖，请查看标签上的 “无糖 ”或 “不
加糖 ”字样。大罐的苹果酱比单杯的更实惠。

在煮熟的热麦片或烘焙食品中加入苹果酱。用苹果酱拌猪肉和其他肉类，而不要
用可能添加了大量糖的酱料。在煎饼或华夫饼上加苹果酱，而不是糖浆。
** 生香蕉，熟和稍熟
现在购买青香蕉，以便本周晚些时候使用。将香蕉放在牛皮纸袋中会使其更快成
熟。此外，如果香蕉与其他水果存放在一起，也会导致它们更快成熟。过熟的香
蕉做酸奶、冰沙、燕麦粥或全麦煎饼都很美味。现在使用或去皮后放入冰箱备用。

在麦片粥、燕麦粥或酸奶中加入香蕉片。用香蕉和其他水果切块做成水果串。用
小麦面包、香蕉片和您喜欢的坚果黄油制作三明治。制作香蕉 “冰淇淋”，享受
美味。将成熟的香蕉块冷冻，搅拌至顺滑。
** 蓝莓，生吃
冷冻蓝莓可放在密封容器或冷冻袋中的冷冻室中保存 10 - 18 个月。查看包装
上的日期。寻找配料中不含糖的蓝莓。冷冻蓝莓可用于多种用途，无需先解冻，
如冰沙、燕麦粥和酸奶。如果您确实需要解冻蓝莓，只需将所需数量的蓝莓放入
密闭容器中，在冰箱中解冻即可。在当季购买新鲜蓝莓，价格较低，将多余的蓝
莓冷冻起来，以备日后使用。

将牛奶或强化豆奶、冷冻蓝莓和香蕉混合，制作快速美味的冰沙。在煎饼或松饼
面糊中加入解冻的冷冻蓝莓，或在燕麦粥中加入解冻的蓝莓，让早餐更加色香味
俱全。将解冻的冷冻蓝莓与罐装桃子和燕麦片混合，做成令人满意的下午点心。

** 瓜类，哈密瓜，生吃
夏季是哈密瓜上市的季节。当季水果和蔬菜的价格可能较低。成熟的哈密瓜全身
应该略微结实，没有软绵绵的感觉，而且整体应该有甜味。购买并切开一个完整
的哈密瓜，而不是购买预先切好的哈密瓜容器，也许能节省开支。选择最适合您
家庭的方案。切之前，先用凉自来水彻底擦洗哈密瓜的外表面。将整个哈密瓜在
室温下保存至成熟，最多可保存两周。将切好的哈密瓜放入密闭容器中冷藏，以
便在 5 天内使用。

将哈密瓜丁和其他喜欢的水果串成串。食用时可搭配酸奶蘸酱。哈密瓜是花园沙
拉的绝佳甜食。试试甜瓜莎莎酱！将哈密瓜切丁，加入切碎的红洋葱、香菜和青
柠汁液，调制成香味浓郁的莎莎酱，可与海鲜搭配。

** 葡萄柚汁，红色，非强化，非浓缩，冷藏
西柚是冬季的时令水果。自购买之日起，西柚可在室温下储存 10 天，或在冰箱
中储存 3 周。挑选成熟的西柚时，要看它的颜色是否较深，挤压果实时是否会
有一点松动。柚子摸起来越硬，说明成熟度越低。您知道吗？葡萄柚因其在树上
生长的方式而得名：像一串葡萄一样簇拥在一起。西柚会与一些常见药物产生相
互作用。请咨询您的医生，看看对您是否安全。

西柚本身就是一种很好的零食。切成片，或舀出部分。如果您想给它调味，可以
尝试撒一点肉桂粉甚至黑胡椒！西柚还能为沙拉增色添彩。在自选的生菜上放上
去皮切丁的西柚、鹰嘴豆和少量醋汁，是一道清爽的美食。在柚子片上刷上橄榄
油，然后将柚子片烧烤或炙烤，与煮熟的鸡肉或鱼肉一起食用。
** 芒果，阿陶勒佛，去皮，生吃
夏季和秋季是芒果上市的季节。自购买之日起，芒果可在室温下存放 5 天，或
在冰箱中存放 1 周。要挑选成熟的芒果，重点在于手感，而不是颜色。拿起一
个轻轻捏一下。成熟的芒果会稍有弹性，而不成熟的芒果会比较硬。您可以提前
做好计划，在购物时选择成熟度较低的芒果；回家后只需把它们装进纸袋里，等
待它们成熟。

用芒果丁、红洋葱、香菜、青柠汁、墨西哥辣椒（可选）或红辣椒制作芒果莎莎
酱。浇在鱼肉、鸡肉或猪肉上食用。如果想冷冻，可将芒果切片与橙汁混合。用
冰棒棍或吸管放入冰块盘中冷冻。制作芒果冰沙：混合 1 杯橙汁、½ 杯低脂酸
奶和一根香蕉。加入 6 块冰和 1 个芒果丁。再次搅拌。经典三明治的新花样：
烤全麦面包，涂上花生酱，加入芒果片。
** 橙
冬季是橘子上市的季节。自购买之日起，橘子可在室温下存放一周，在冰箱中可
存放三周。购买一袋橙子比单独购买橙子通常更省钱。

保持简单--橘子片本身就很美味。放学或下班后，吃点橙子当甜点。在沙拉上放
上橙子块，增添风味。在水壶中加入橙子片，让饮料更加清爽。

** 桃子，黄，生
未开封的桃子罐头可在储藏室中存放 12-18 个月。请查看标签上的日期。开封
后，可在冰箱中存放 5-7 天。为了减少添加的糖分，可以选择 100%果汁或水罐
装的桃子，而不是糖浆罐装的桃子。罐装桃子可能比单个桃子杯更实惠，但桃子
杯也是外出时的健康零食选择。选择最适合您家庭的方案。

罐装桃子片是冷热麦片、煎饼、华夫饼、低脂酸奶或松软干酪的绝佳配料。在速
溶燕麦粥中加入水蜜桃罐头丁，可做成快速美味的早餐。桃子温热后味道更佳！
沥干桃肉，撒上肉桂粉。在烤箱中烤 5-10 分钟，直至呈浅棕色。将桃子罐头与
低脂酸奶、香蕉和冰块一起倒入搅拌机，搅拌成美味的冰沙。

** 梨，生，巴特利
未开封的梨罐头可在储藏室中存放 12-18 个月。请查看标签上的日期。开封后，
可在冰箱中存放 5-7 天。为了减少糖的添加，可以选择 100%果汁或水而不是糖
浆的梨罐头。罐装梨比单个杯装梨更实惠，但单个杯装梨也是外出时的健康零食
选择。选择最适合您家庭的方案。

用梨罐头切丁作为全麦华夫饼、燕麦粥或酸奶的配料。在酸奶或松软干酪上放上
罐头梨丁，作为简易零食。将梨罐头与柠檬汁和肉桂粉混合，煮成简单快捷的梨
黄油。

** 菠萝，生吃
未开封的菠萝罐头可在储藏室中存放 12-18 个月。请查看标签上的日期。开封
后，可在冰箱中存放 5-7 天。为了减少添加的糖分，可以选择 100%果汁或水罐
装的菠萝，而不是糖浆罐装的菠萝。

在酸奶或松软干酪中加入菠萝罐头作为点心。自制菠萝冰糕！将罐装菠萝块冷冻，
然后搅拌至顺滑。在鸡肉三明治或汉堡上放一个罐装菠萝圈，甜味与美味完美结
合。

* 蔬菜和蔬菜制品
** 生甜菜
中等和较大的甜菜适合烹饪；无论采用哪种烹饪方法，根部过大的甜菜都过于木
质，不适合食用。甜菜要光滑、坚硬、圆度一致，没有切口和瘀伤。去掉甜菜叶，
立即使用。切掉顶部的甜菜用单独的塑料袋装好，放在冰箱最冷的地方。这些甜
菜可保存一周。甜菜煮熟后可以去皮冷冻。烹饪前要清洗和擦洗甜菜。甜菜在烹
饪后去皮效果最好，而且会弄脏很多接触到的东西。如果想避免弄脏手，可以戴
上手套。

嫩甜菜可以生吃，但在食用前通常要煮熟、蒸熟或烤熟。煮熟的甜菜可以切片，
作为蔬菜放在盘子的一边。

** 生西兰花
冷冻西兰花可在冰箱中储存 10-18 个月。购买大袋冷冻西兰花通常可以节省开
支。每次只解冻您需要的部分。冷冻西兰花通常有三种切法：茎（茎和花）、花
（只有顶部部分）和切碎（茎和花切丁）。选择最适合您家庭口味和预算的一种。

将冷冻西兰花放在炉子上蒸，直到呈浓郁的深绿色--通常为 5-8 分钟。加入少
许调味料即可享用！西兰花意面： 在烹饪时间结束前三分钟左右，将冷冻西兰
花放入煮沸的意大利面锅中。根据需要调味。烤西兰花：将冷冻西兰花用油和盐
拌匀。铺在烤盘上，用华氏 400 度烤至焦黄。

** 胡萝卜，成熟，生
胡萝卜四季皆宜--冬季、春季、夏季和秋季 胡萝卜自购买之日起可在冰箱中存
放 2-3 周 胡萝卜有新鲜的、冷冻的或罐装的

胡萝卜条或小胡萝卜是一种很好的便携式零食。上班、参加活动或旅行时都可以
带着吃。在您喜欢的汤、沙拉或凉拌菜中加入胡萝卜丁或胡萝卜丝。胡萝卜非常
适合蘸酱吃！试试鹰嘴豆泥、花生酱或用酸奶混合香草和香料DIY的蘸酱。

** 羽衣甘蓝，生
羽衣甘蓝在春季、冬季和秋季都是当季蔬菜。当季水果和蔬菜的价格可能会更低。
选择叶色深绿、没有发黄的菜束。自购买之日起，新鲜的羽衣甘蓝可在冰箱中储
存 4 天。购买成捆的羽衣甘蓝并将其切碎，而不是购买预先切好的袋子，也许
能节省开支。

需要快速配菜？将羽衣甘蓝与鸡汤、洋葱和辣椒粉在锅中混合。用小火慢炖，直
到可以食用。在任何一碗汤上放一把羽衣甘蓝，让汤的热气快速蒸熟羽衣甘蓝，
增加营养。当意大利面还有 5 分钟就煮好时，将切碎的羽衣甘蓝放入意大利面
锅中。用少量橄榄油和您喜欢的香草和香料调味。羽衣甘蓝是任何炒菜的好帮手。
可以尝试将它们与大蒜、洋葱、蜂蜜、鸡胸肉或豆腐一起炒。

** 黄瓜，带皮，生吃
夏季是黄瓜上市的季节。当季水果和蔬菜的价格可能较低。自购买之日起，黄瓜
可在冰箱中存放 4-6 天。选择颜色深绿、结实的黄瓜。你知道黄瓜深绿色的表
皮中含有营养和纤维吗？因此，可以省去去皮的步骤，连皮一起吃，但别忘了洗
干净。

将黄瓜切片，然后淋上酸橙汁，撒上辣椒粉。将去皮去籽的黄瓜切成细丝，拌入
鸡肉、虾或金枪鱼沙拉中。在您喜欢的三明治或卷饼中加入黄瓜片，增加脆感。
制作黄瓜独木舟，是一种有趣的小吃。将黄瓜纵向切成两半，用勺子挖出黄瓜籽。
填入松软干酪和西红柿丁。将黄瓜与鹰嘴豆泥搭配在一起，是一种饱腹又美味的
零食。

** 四季豆、豆角、绿豆、生豆、串豆
夏季和秋季是四季豆上市的季节。当季的水果和蔬菜价格可能较低。青豆自购买
之日起可在冰箱中储存 5 天。青豆有新鲜的、冷冻的和罐装的。

在平底锅中加入橄榄油和柠檬汁翻炒青豆，是一道简单的配菜。将青豆剪去两端，
蒸至变软，然后拌上您喜欢的醋汁。将冷冻青豆拌入您喜欢的汤或炖菜中，可增
加蔬菜的分量。

** 卷心菜，绿色，生
卷心菜的季节为冬季、春季和秋季。自购买之日起，卷心菜可在冰箱中存放 1-2
周。购买并切碎卷心菜头，而不是购买预先切好的袋装卷心菜，可以节省开支。

用卷心菜丝、油、醋和香料快速制作沙拉。将卷心菜丝与洋葱和您喜欢的调味料
一起翻炒，直到卷心菜变软，成为一道美味的配菜。在沙拉、汤、墨西哥玉米饼
或三明治上淋上薄薄的卷心菜丝，让它们变得更加松脆。

** 马铃薯，金色，无皮，生
马铃薯在秋冬季节上市，但全年都可以购买。从购买之日起，马铃薯可在储藏室
存放 1-2 个月。马铃薯有新鲜的、冷冻的和罐装的。购买一袋马铃薯往往比单
独购买省钱。

微波炉加热： 清洗马铃薯，用叉子扎几下。放在盘子上微波 10 分钟，中途翻
面。调味后即可享用！烤箱烘烤： 清洗马铃薯，切成 1 英寸见方的小块。在碗
中加入油和您喜欢的香料。摄氏 230 度烤 30 分钟。水煮 将土豆洗净切成 1
英寸见方的小块。煮至可以用叉子轻松刺穿。与少许无盐人造黄油和调味料混合。

** 瓜类，夏季，绿色，西葫芦，包括皮，生
夏季是夏南瓜的上市季节。当季的水果和蔬菜价格可能较低。选择表皮没有褶皱
或软点的坚硬南瓜。夏季南瓜在室温下可存放 2 天，在冰箱中可存放 5 天。使
用前要清洗干净。夏季南瓜有多种类型，包括chayote、cousa、crookneck、
pattypan 和西葫芦。

将蒸熟的夏季南瓜加入您最喜欢的意大利面酱中，浇在意大利面条上，就能轻松
完成一顿周未晚餐。用削皮器将生的西葫芦或牛角瓜削成薄片，可以为沙拉或三
明治增添脆感。用橄榄油和您喜欢的调味料炒夏季南瓜片，可作为一道快速配菜。

* 豆类和豆类产品
** 干豆，黑豆（0% 水分）

罐装豆子自购买之日起可在储藏室存放 5 年。请查看罐头上的日期。开封后，
将豆子放入冰箱冷藏，并在 4 天内使用。为减少钠（盐）含量，使用罐装豆子
前要用滤网沥干并冲洗干净。一些商店也可能出售低钠（盐）产品。请查看标签
上的 “少钠 ”或 “无盐添加 ”字样。购买商店品牌或更大罐的豆子可能会更省钱。
选择最适合您家庭的食物。

在鸡蛋中加入黑豆，用玉米饼裹上西红柿丁和切达干酪丝（低脂），做成美味的
早餐卷饼。将黑豆、莎莎酱、酸橙汁、孜然芹和香菜混合在一起，制成黑豆蘸酱。
与玉米片或生蔬菜一起食用。“豆子和米饭 ”或 “米饭和豆子”......无论怎么说，
黑豆和米饭都是很好的组合，也是美味而营养的一餐。将黑豆与甜椒丁、您喜欢
的香草和香料混合，做成黑豆饼。

** 豆，干，深红色芸豆（0%水分）
罐装豆子自购买之日起可在储藏室存放 5 年。请查看罐头上的日期。开封后，
将豆子放入冰箱冷藏，并在 4 天内使用。为减少钠（盐）含量，使用罐装豆子
前要用滤网沥干并冲洗干净。一些商店也可能出售低钠（盐）产品。请查看标签
上的 “少钠 ”或 “无盐添加 ”字样。购买商店品牌或更大罐的豆子可能会更省钱。
选择最适合您家庭的食物。

在您最喜欢的意大利面酱中加入菜豆，然后用勺子舀在全麦意大利面上。配上花
园沙拉或蒸蔬菜，就是一顿完整的晚餐。如果想做一道简单快捷的配菜，可将罐
装玉米、芸豆（沥干并洗净）和辣椒粉搅拌在一起。芸豆是辣椒酱的绝佳配料。
无论您喜欢肉酱辣椒还是素辣椒，加入菜豆都能增加纤维和风味。在饭菜中加入
菜豆可以快速补充蛋白质。将菜豆与调味汁（或辣调味汁）和蔬菜混合，可制成
快速玉米卷沙拉。

** 小扁豆，干
自购买之日起，扁豆可在储藏室中存放一年。烹饪后，扁豆可在冰箱中存放 5
天。小扁豆在大多数食品店的干豆和罐装豆类区都能买到。与干豆不同，干扁豆
无需预先浸泡，烹饪起来也很快。烹饪前将干扁豆冲洗干净。

基本烹饪方法：将 1 杯洗净的干扁豆与 3 杯水混合。煮沸后用小火慢炖 30 分
钟直至变软。小扁豆可加入辣椒、墨西哥玉米饼、酱汁和肉卷中，或替代肉类。
将扁豆与米饭、蔬菜或面食搭配在一起，还可以做成一餐。

** 花生酱，奶油状
未开封的花生酱通常可以在储藏室里存放两年。查看标签上的日期。开封后的花
生酱可在储藏室存放 2 个月。如果花生酱标注为天然花生酱，可在冰箱中存放
4 个月。购买商店品牌的花生酱和较大的容器通常可以省钱。

花生酱是苹果、梨片或胡萝卜、芹菜条等松脆水果和蔬菜的绝佳蘸酱。用花生酱
和全麦饼干做成迷你三明治，作为外出时的简易零食。用花生酱做花生酱配面条。

** 花生，生
未开封的花生可存放在储藏室中，直至包装上的使用期限。开封后的花生可在储
藏室中存放 2 周，或在冰箱中存放 4 周。为减少钠（盐）含量，可选择干烤、
无盐的花生。购买大容器的花生可能会省钱。只购买您知道可以在上述时限内使
用的花生。

将花生、干果（如葡萄干）和烤燕麦片混合在一起，做成简单便携的混合食品。
将花生切成大块或压碎，用作汤、炖菜和沙拉的配料。在炒蔬菜时拌入花生，为
蔬菜增添充满蛋白质的松脆口感。配上糙米饭或全麦面条。在酸奶冻糕中加入压
碎的花生，增加酥脆感。

** 普通豆，干豆，品托豆（0% 水分）
罐装豆子自购买之日起可在储藏室存放 5 年。请查看罐头上的日期。开封后，
将豆子放入冰箱冷藏，并在 4 天内使用。为减少钠（盐）含量，使用罐装豆子
前要用滤网沥干并冲洗干净。一些商店也可能出售低钠（盐）产品。请查看标签
上的 “少钠 ”或 “无盐添加 ”字样。购买商店品牌或更大罐的豆子可能会更省钱。
选择最适合您家庭的做法。

将一罐松豆（沥干并洗净）捣碎，加入辣椒粉和大蒜粉调味。涂抹在芹菜条上，
再淋上辣调味汁，就成了香脆的零食。制作简单的三豆沙拉。将松豆、青豆、菜
豆各一罐，加上洋葱丁和西红柿丁，再配上您喜欢的醋汁。在汤、炖菜、辣菜甚
至意大利面沙拉中加入品豆，可增加风味和口感。

* 烘焙产品
** 面包，全麦，商业预制
面包在储藏室里可以存放 5 天左右，在冰箱里可以存放 3 个月。如果面包打折，
可以多买一块面包冷冻起来。当您准备使用冷冻面包时，只需在室温下解冻或将
冷冻面包片放入烤面包机中即可。选择全麦面包时，要看标签上的第一种成分是
“全麦 ”还是 “全谷物”。

在全麦吐司上放坚果黄油和水果，如香蕉片或苹果片。自制全麦面包丁。在面包
块上淋油，撒上大蒜和洋葱粉。烘烤直至烤熟。在小麦面包上尝试新的三明治创
意：烤蔬菜和奶酪、豆腐和番茄，或鹰嘴豆泥和火鸡肉。

* 谷物和面食
** 糙米，长粒，未浓缩，生米
糙米磨去外层可以制得白米；但因糙米保存完整的稻米营养，富含蛋白质、脂质、
纤维及维生素B1等，所以是比白米更健康的食物。其口感较硬，对很多人来说味
道不如白米，烹调也需要更久。

糙米可在储藏室存放一年。煮熟后，可在冰箱中存放 4 - 6 天。糙米有多种烹
饪方法，包括速溶或普通烹饪。普通大米可能是最便宜的选择。选择最适合您家
庭的烹饪方式。

将煮熟的糙米饭加入蔬菜汤中，做成快餐。用糙米、蔬菜、您喜欢的蛋白质食物
制作您自己的卷饼碗，上面放上奶酪丝或混合了香草和调味料的原味酸奶。早餐
吃糙米饭？是的！用牛奶、葡萄干和肉桂加热，或者尝试自己的创意。

** 甜玉米，黄粒和白粒，新鲜，生吃
自购买之日起，未开封的罐装玉米可在储藏室存放 2-5 年。打开后，可在冰箱
中存放 3-4 天。您知道吗？罐装玉米已经完全煮熟，因此无需进一步烹饪即可
放心食用。罐装蔬菜非常适合随身携带。查看标签上的 “低钠 ”或 “无盐添加 ”
字样，或冲洗罐装蔬菜以减少其钠（盐）含量。

用少量油将罐装玉米与青辣椒、番茄和洋葱一起炒，做成一道色彩丰富的配菜。
用罐装玉米、切碎的蔬菜、豆类和醋汁制作快速意面沙拉。在汤、辣椒酱、辣调
味汁、杂烩汤、玉米饼、卷饼碗中加入玉米。将玉米与利马豆一起做成
succotash。

** 面粉，玉米，黄色，细粉，加营养剂
玉米面可密封保存在阴凉避光的储藏室中长达 6 个月，或在冰箱中保存长达 1
年。玉米面由干玉米制成，有黄色和白色两种。

玉米面是一种多用途的烘焙配料。可用于制作松饼、烤饼、饼干和蛋糕。用玉米
粉制作香脆的烤秋葵。将玉米面与辣椒粉和大蒜粉混合。将秋葵块放入混合物中
滚动，然后在摄氏200度下烘烤25分钟。将玉米面、面粉和您喜欢的调味料混合
在一起，做成鸡肉、猪肉或鱼肉的裹粉。试试用玉米面做热早餐麦片！将 1 杯
水、1 杯玉米面和一小撮盐混合。将混合物慢慢倒入 3 杯沸水中，不断搅拌。
煮至粘稠，然后加糖浆食用。

** 燕麦、全谷物、轧制、老式燕麦片
干燕麦片可在储藏室中存放 12 个月。购买罐装燕麦片而不是单包燕麦片通常可
以省钱。为了减少添加糖，您可以购买原味燕麦片，然后在家里添加自己喜欢的
调味料。

燕麦片不仅仅是早餐！可以作为配菜，也可以混合配料做成一菜一饭。做成甜食：
加入水果（新鲜水果、干果或解冻的冷冻水果）、肉桂、坚果碎或您最喜欢的坚
果黄油。做成咸味的：试着在烹饪时加入鸡蛋、葱，并在上面撒上奶酪丝。燕麦
片可以在一些食谱中代替面包屑，如肉饼。

** 意大利面，面粉，全麦，未浓缩
未煮熟的干意面可在储藏室中存放 1 年。煮熟后，可在冰箱中存放 3-5 天。在
标签上寻找 “全谷物 ”或 “全麦 ”面粉。购买商店品牌的面粉可能会更省钱。

煮意大利面时，在最后 5 分钟加入冷冻蔬菜，这样一锅菜就会变得丰富多彩。
将煮熟的意大利面条与罐装金枪鱼、蔬菜、油和调味料混合，做成快餐。做一道
简单的白豆意大利面：将煮熟的意大利面、沥干/漂洗过的小扁豆、罐装番茄丁、
罐装玉米和油混合在一起。根据个人喜好进行调味。

** 美洲菰米，干，生
北美产的菰属植物（主要是沼生菰和水生菰）的颖果称为美洲菰米，俗称野米。

野米的谷粒又长又黑，带有坚果的香味，可用于多种用途。野米可在储藏室中存
放 1 年。煮熟后，可在冰箱中存放 4 - 6 天。

野米可以煮熟后单独食用，也可以用来做汤、砂锅菜、馅料或皮拉夫。在鸡汤或
蔬菜汤中加入煮熟的野米，可作为快餐。用煮熟的野米、您喜欢的蔬菜和奶酪制
作您自己的饭碗。

* 乳制品和蛋制品
** 酪乳，低脂
酪乳应冷藏，必须在开封后 7-10 天内使用。请查看容器上的保质期。自购买之
日起，酪乳可冷冻 3 个月。酪乳有多个品种。可选择低脂或脱脂型。

用柠檬汁、橄榄油和香草制作简单的酪乳调味汁。在装满新鲜蔬菜的花园沙拉上
轻轻淋上一点。酪乳可以很好地腌制肉类，因为微酸有助于嫩化肉类。与您最喜
欢的调味料混合后，可以用来烤鸡肉或红烧肉。酪乳为土豆泥增添了丰富的奶油
质感和浓郁的香味。在您喜欢的土豆泥食谱中，用它代替牛奶试试吧。

** 切达干酪
切达奶酪可在冰箱中存放 1 个月。切达奶酪自购买之日起可冷冻 3-4 个月。解
冻后，请在 3 天内使用。对于奶酪丝，您可以在打折时购买大袋或多袋，以节
省开支。在冰箱的密闭容器中存放适量的奶酪丝，然后将剩余的奶酪丝冷冻起来。

试试把火鸡肉放在全麦面包上，再放一片低脂切达干酪，这就是一顿简单的午餐。
在全麦饼干上放一小片奶酪和苹果。用烤过的全麦面包、奶酪和鸡蛋做快速早餐
三明治。在蒸西兰花或球芽甘蓝等蔬菜上撒一点奶酪，可增加风味。

** 乳酪、松软干酪、低脂干酪、2% 乳脂干酪
棉花干酪可在冰箱中存放 2 周（未开封）或 1 周（已开封）。寻找低脂或脱脂
的品种。如果您经常食用松软干酪，您可以购买大桶而不是小盒或独立容器来节
省开支。选择最适合您家庭的口味。

将松软干酪涂在全麦饼干上，再放上您喜欢的蔬菜。在松软干酪上放上桃子罐头、
柑橘或香蕉片。在炒鸡蛋或意大利面中加入一勺松软干酪，以增加风味和蛋白质。

** 牛奶，低脂，液体，2% 乳脂，添加维生素 A 和维生素 D
牛奶应冷藏，开封后必须在 7 天内使用。请查看容器上的保质期。牛奶自购买
之日起可冷冻 3 个月。如果牛奶打折，可再买一个容器。倒出少量牛奶，让液
体膨胀，然后冷冻容器。在冰箱中解冻过夜，摇匀后在 3 天内使用。

用牛奶煮燕麦片或糁等热麦片，使其口感细腻。用餐时喝牛奶，可作为提神饮料。
用牛奶泡茶或咖啡。

** 鸡蛋，A 级，大个，全蛋
商店购买的鸡蛋应存放在冰箱中，自购买之日起可使用 3-5 周。检查纸盒上的
保质期。购买前打开纸盒，检查鸡蛋是否破裂。购买大盒鸡蛋通常可以省钱。

用辣椒、洋葱和莎莎酱炒鸡蛋。可以直接食用，也可以卷在全麦玉米饼里作为便
餐。煮熟的鸡蛋是很好的零食，也可以加入沙拉中补充蛋白质。一次煮几个，放
在冰箱里保存。鸡蛋是一种多用途蛋白质食物，可用于烘焙菜肴、三明治、煎蛋
卷，或炒入米饭和面条中。

** 希腊酸奶，原味，脱脂
希腊酸奶应冷藏，自购买之日起可存放 1-2 周。请查看包装上的保质期。不建
议冷冻希腊酸奶。购买大桶希腊酸奶而不是单个容器的希腊酸奶通常可以节省开
支。选择最适合您家庭的食物。

用原味希腊酸奶做玉米饼、皮塔饼、辣椒、土豆等的配料。在您最喜欢的金枪鱼
沙拉或意大利面沙拉食谱中加入希腊酸奶，可增加钙质、香浓的味道和奶油质感。
用原味希腊酸奶制作各种美味顺滑的蘸酱、涂抹酱和沙拉酱。在希腊酸奶中加入
罐装桃、梨或菠萝，可作为健康零食。

** 酸奶，原味，脱脂
酸奶应冷藏，自购买之日起可存放 1-2 周。查看包装上的保质期。自购买之日
起，酸奶可冷冻 1-2 个月。酸奶可在原容器中冷冻。准备使用时，只需在冰箱
中解冻过夜，搅拌均匀，并在 3 天内食用即可。购买大桶酸奶而不是单独的容
器或管装酸奶，通常可以节省开支。选择最适合您家庭的食物。

用纯酸奶做玉米饼、皮塔饼、辣椒、土豆等的配料。准备水果和酸奶冰沙，供放
学后或下班后食用。用纯酸奶和自己喜欢的香草和香料自制蘸酱。用纯酸奶、黄
瓜碎（榨干）、柠檬汁、油、大蒜和香料自制 tzatziki 酱。

* 鱼类和贝类产品
** 鱼，金枪鱼，淡水罐头，沥干固形物
罐装金枪鱼可在储藏室中存放 3 年，自购买之日起算。选择甲基汞含量比长鳍
金枪鱼低的浅色大块金枪鱼罐头。购买商店品牌的罐头，或选择较大的罐头或捆
绑罐头，通常可以节省开支。

在花园沙拉中加入罐装金枪鱼，可作为简单的午餐。与意大利面一起食用。制作
金枪鱼砂锅或用于通心粉沙拉。将金枪鱼罐头与原味希腊酸奶或蛋黄酱和切碎的
芹菜混合。将混合物涂抹在全麦面包上，再配上黄瓜片，制成便携式三明治。

** 鱼、鲶鱼、农场饲养、生
鲶鱼是一种白鱼，味道清淡，易于烹制出多种不同的菜肴。购买冷冻鱼可以节省
开支。在商店的冷冻海鲜区寻找。将冷冻鱼放入冰箱解冻。根据鱼的大小，完全
解冻可能需要 1-2 天的时间。

鲶鱼片可以烤、烧或烤。试试鲶鱼块！将鱼片拌入面包屑或玉米粉中烘烤，作为
午餐或晚餐食用。自己制作黑鲶鱼！用辣椒粉和其他香料调味，然后在炉灶上烹
制。配上糙米饭和蔬菜，就是一顿完整的晚餐。

** 鱼、鲑鱼、大西洋鲑鱼、农场饲养、生
三文鱼是一种片状鱼肉，颜色从橙色到深红色不等。三文鱼是欧米伽-3 脂肪酸
的来源，作为健康饮食的一部分，欧米伽-3 脂肪酸有助于降低患心脏病的风险。
购买冷冻鱼可能会省钱。在商店的冷冻海鲜区寻找。将冷冻鱼放入冰箱解冻。根
据鱼的大小，完全解冻可能需要 1-2 天的时间。

三文鱼片可以烤、烧或烤。用柠檬汁和您喜欢的调料调味三文鱼片。在平底锅中
倒入橄榄油加热，将三文鱼每面煎至内部温度达到 63°C。将三文鱼片皮朝下放
在铝箔纸上。在上面淋上油、洋葱片、柠檬胡椒或其他调料。在 180°C 温度下
烘烤 15-20 分钟，直至鱼肉温度达到 63°C。

** 鱼、黑线鳕鱼、罗非鱼、农场饲养、生
白鱼的味道通常比较清淡，容易用多种方法烹制。选择甲基汞含量较低的鱼类品
种，如鲶鱼、比目鱼/鲽鱼、黑线鳕、无须鳕、鲻鱼、狭鳕、罗非鱼和鳕鱼。新
鲜鱼在购买后可在冰箱中保存 3 天，或在冷冻室中保存 6 个月。购买冷冻鱼可
能会省钱。在商店的冷冻海鲜区寻找。将冷冻鱼放入冰箱解冻。根据鱼的大小，
可能需要 1-2 天才能完全解冻。

将鱼片拌入面包屑中，烤制午餐或晚餐。制作鱼肉卷，可作为美味有趣的一餐。
淋上番茄丁、洋葱和少许酸橙汁。煎鱼是一道简单快捷的周末晚餐。在鱼的两面
撒上您喜欢的调味料，然后用少量橄榄油煎至内部温度达到 63°C。

* 禽肉产品
** 鸡肉，肉鸡或油炸鸡，鸡腿，仅肉，煮熟，炖煮
** 鸡腿肉，去骨，去皮，生的
未煮熟的鸡肉应冷藏，自购买之日起可存放 1-2 天。煮熟后的鸡肉应冷藏并在
3-4 天内使用，也可冷冻并在 2-6 个月内使用。购买鸡肉时，鸡腿和鸡腿通常
比鸡胸肉便宜。在打折时购买鸡胸肉。如果您的商店正在进行鸡肉大减价，您可
以多买一些，未经烹饪就冷冻起来，最长可保存 9 个月。

将所有家禽煮至最低安全内部温度 165 华氏度（74 摄氏度）。用鸡肉做汤和炖
菜。加入番茄罐头和不同的调味料，可以做出各种各样的菜肴。用煮熟的鸡肉做
沙拉、墨西哥卷饼的馅料或意大利面酱。在烧烤或炙烤鸡肉前，在鸡肉上撒上大
蒜粉和胡椒粉等调味料。
