#+title: 实惠健康的未加工食品
#+date: 2025-01-24T11:11:42+01:00
#+lastmod: 2025-01-24T11:11:42+01:00
# ISO 8601 date use output from
# C-u M-! date -Iseconds
#+draft: false
#+tags[]:

本文介绍了可广泛获得的未加工或微量加工食品，包括其储存、季节性和烹饪方
法。

Source: https://www.myplate.gov/shopsimple/foods/all
# more

* 钠摄入量
https://medlineplus.gov/ency/article/002415.htm

健康成人的钠摄入量应限制在每天 2,300 毫克。患有高血压的成年人每天的钠
摄入量不应超过 1,500 毫克。患有充血性心力衰竭、肝硬化和肾病的人可能需
要更少的钠。

饮食中的钠（称为膳食钠）以毫克（mg）为单位。食盐的钠含量为 40%。一茶匙
（5 毫升）食盐含有 2,300 毫克钠。

钠天然存在于大多数食物中。钠的最常见形式是氯化钠，也就是食盐。牛奶、甜
菜和芹菜中也天然含有钠。饮用水中也含有钠，但含量取决于水源。钠还添加到
许多食品中。这些添加物包括谷氨酸钠（味精）、亚硝酸钠、糖精钠、小苏打
（碳酸氢钠）和苯甲酸钠。喼汁、酱油、洋葱盐、大蒜盐和肉汤块中都含有这些
物质。

熏肉、香肠和火腿等加工肉类以及罐装汤和蔬菜也含有添加钠。包装饼干、点心
蛋糕和甜甜圈等加工烘焙食品通常也含有较高的钠。快餐食品的钠含量通常很高。

饮食中钠含量过高可能导致 某些人会患高血压，患有心力衰竭、肝硬化或肾病
的人会严重积水。

* 水果和果汁
** 苹果酱，无糖，添加维生素 C
未开封的苹果酱可在储藏室中存放 12 - 18 个月。请查看标签上的日期。开封
后，可在冰箱中存放 7-10 天。为减少添加糖，请查看标签上的 “无糖 ”或 “不
加糖 ”字样。大罐的苹果酱比单杯的更实惠。

在煮熟的热麦片或烘焙食品中加入苹果酱。用苹果酱拌猪肉和其他肉类，而不要
用可能添加了大量糖的酱料。在煎饼或华夫饼上加苹果酱，而不是糖浆。
** 生香蕉，熟和稍熟
现在购买青香蕉，以便本周晚些时候使用。将香蕉放在牛皮纸袋中会使其更快成
熟。此外，如果香蕉与其他水果存放在一起，也会导致它们更快成熟。过熟的香
蕉做酸奶、冰沙、燕麦粥或全麦煎饼都很美味。现在使用或去皮后放入冰箱备用。

在麦片粥、燕麦粥或酸奶中加入香蕉片。用香蕉和其他水果切块做成水果串。用
小麦面包、香蕉片和您喜欢的坚果黄油制作三明治。制作香蕉 “冰淇淋”，享受
美味。将成熟的香蕉块冷冻，搅拌至顺滑。
** 蓝莓，生吃
冷冻蓝莓可放在密封容器或冷冻袋中的冷冻室中保存 10 - 18 个月。查看包装
上的日期。寻找配料中不含糖的蓝莓。冷冻蓝莓可用于多种用途，无需先解冻，
如冰沙、燕麦粥和酸奶。如果您确实需要解冻蓝莓，只需将所需数量的蓝莓放入
密闭容器中，在冰箱中解冻即可。在当季购买新鲜蓝莓，价格较低，将多余的蓝
莓冷冻起来，以备日后使用。

将牛奶或强化豆奶、冷冻蓝莓和香蕉混合，制作快速美味的冰沙。在煎饼或松饼
面糊中加入解冻的冷冻蓝莓，或在燕麦粥中加入解冻的蓝莓，让早餐更加色香味
俱全。将解冻的冷冻蓝莓与罐装桃子和燕麦片混合，做成令人满意的下午点心。

** 瓜类，哈密瓜，生吃
夏季是哈密瓜上市的季节。当季水果和蔬菜的价格可能较低。成熟的哈密瓜全身
应该略微结实，没有软绵绵的感觉，而且整体应该有甜味。购买并切开一个完整
的哈密瓜，而不是购买预先切好的哈密瓜容器，也许能节省开支。选择最适合您
家庭的方案。切之前，先用凉自来水彻底擦洗哈密瓜的外表面。将整个哈密瓜在
室温下保存至成熟，最多可保存两周。将切好的哈密瓜放入密闭容器中冷藏，以
便在 5 天内使用。

将哈密瓜丁和其他喜欢的水果串成串。食用时可搭配酸奶蘸酱。哈密瓜是花园沙
拉的绝佳甜食。试试甜瓜莎莎酱！将哈密瓜切丁，加入切碎的红洋葱、香菜和青
柠汁液，调制成香味浓郁的莎莎酱，可与海鲜搭配。

** 葡萄柚汁，红色，非强化，非浓缩，冷藏
西柚是冬季的时令水果。自购买之日起，西柚可在室温下储存 10 天，或在冰箱
中储存 3 周。挑选成熟的西柚时，要看它的颜色是否较深，挤压果实时是否会
有一点松动。柚子摸起来越硬，说明成熟度越低。您知道吗？葡萄柚因其在树上
生长的方式而得名：像一串葡萄一样簇拥在一起。西柚会与一些常见药物产生相
互作用。请咨询您的医生，看看对您是否安全。

西柚本身就是一种很好的零食。切成片，或舀出部分。如果您想给它调味，可以
尝试撒一点肉桂粉甚至黑胡椒！西柚还能为沙拉增色添彩。在自选的生菜上放上
去皮切丁的西柚、鹰嘴豆和少量醋汁，是一道清爽的美食。在柚子片上刷上橄榄
油，然后将柚子片烧烤或炙烤，与煮熟的鸡肉或鱼肉一起食用。
** 芒果，阿陶勒佛，去皮，生吃
夏季和秋季是芒果上市的季节。自购买之日起，芒果可在室温下存放 5 天，或
在冰箱中存放 1 周。要挑选成熟的芒果，重点在于手感，而不是颜色。拿起一
个轻轻捏一下。成熟的芒果会稍有弹性，而不成熟的芒果会比较硬。您可以提前
做好计划，在购物时选择成熟度较低的芒果；回家后只需把它们装进纸袋里，等
待它们成熟。

用芒果丁、红洋葱、香菜、青柠汁、墨西哥辣椒（可选）或红辣椒制作芒果莎莎
酱。浇在鱼肉、鸡肉或猪肉上食用。如果想冷冻，可将芒果切片与橙汁混合。用
冰棒棍或吸管放入冰块盘中冷冻。制作芒果冰沙：混合 1 杯橙汁、½ 杯低脂酸
奶和一根香蕉。加入 6 块冰和 1 个芒果丁。再次搅拌。经典三明治的新花样：
烤全麦面包，涂上花生酱，加入芒果片。
** 橙
冬季是橘子上市的季节。自购买之日起，橘子可在室温下存放一周，在冰箱中可
存放三周。购买一袋橙子比单独购买橙子通常更省钱。

保持简单--橘子片本身就很美味。放学或下班后，吃点橙子当甜点。在沙拉上放
上橙子块，增添风味。在水壶中加入橙子片，让饮料更加清爽。

** Peaches, yellow, raw
Unopened canned peaches can be stored in the pantry for 12-18
months. Check the date on the label.
After opening, store in the refrigerator for 5-7 days.
To cut down on added sugars, look for peaches canned in 100% juice or
water, rather than syrups.
Cans of peaches can be more affordable than individual cups, however
cups can be a healthy snack choice on the go. Choose the option that
works best for your family.

Canned peach slices are a great addition to hot or cold cereals,
pancakes, waffles, and low-fat yogurt or cottage cheese.  Add diced
canned peaches to your instant oatmeal for a quick and tasty
breakfast.  Peaches taste great warm! Drain peach halves and sprinkle
with cinnamon. Broil in your oven for 5-10 minutes until light brown.
Toss canned peaches into a blender with low-fat yogurt, bananas, and
ice; then blend for a delicious smoothie.
** Pears, raw, bartlett
Unopened canned pears can be stored in the pantry for 12-18
months. Check the date on the label.
After opening, store in the refrigerator for 5-7 days.
To cut down on added sugars, look for pears canned in 100% juice or
water, rather than syrups.
Cans of pears can be more affordable than individual cups, however
cups can be a healthy snack choice on the go. Choose the option that
works best for your family.

Use diced canned pears as a topping for whole wheat waffles, oatmeal,
or yogurt.
Top yogurt or cottage cheese with canned diced pears for an easy
snack.
Combine canned pears with lemon juice and cinnamon to cook down into a
quick and easy pear butter.
** Pineapple, raw
Unopened canned pineapple can be stored in the pantry for 12-18
months. Check the date on the label.
After opening, store in the refrigerator for 5-7 days.
To cut down on added sugars, look for pineapple canned in 100% juice
or water, rather than syrups.

Top yogurt or cottage cheese with canned pineapple for a snack.
Make your own pineapple sorbet! Freeze canned chunks, then blend until
smooth.
Top your chicken sandwich or burger with a canned pineapple ring for a
great sweet-savory combination.

** Strawberries, raw
Frozen strawberries can be stored in the freezer for 10 - 18
months. Check the date on the package.
To cut down on added sugars, check the ingredients list. Look for
strawberries that do not have sugar listed in the ingredients.
Frozen strawberries can be used in many ways without being thawed
first, such as in smoothies.
If you do need to thaw some, place only the amount you need in an
airtight container to thaw slowly in the refrgerator.

Make a parfait! Layer low-fat plain yogurt, whole grain granola, and
thawed frozen strawberries.
Blend milk or fortified soy milk, frozen strawberries, and a banana
for a quick and delicious smoothie.
Add frozen strawberries to a pot with a splash of lemon juice and a
sprinkle of sugar. Simmer until tender, and use as a syrup on whole
wheat pancakes or French toast.
Make a strawberry vinaigrette! Thaw and combine 1 cup diced frozen
strawberries, 2 tbsp apple cider vinegar, 2 tbsp olive oil, and salt
and pepper to taste. Use as a salad dressing or as a marinade for
chicken or pork.

* Vegetables and Vegetable Products
** Beets, raw
Medium- and large-size beets are good for cooking; very large roots
are too woody for eating regardless of cooking method.
Look for smooth, hard, uniformly round beets that are free of cuts and
bruises.
Remove the beet greens and use immediately.  Store beets with their
tops chopped off in individual plastic bags in the coolest part of the
refrigerator. These should last up to one week.
Once cooked, beets can be frozen with their peels removed.
Wash and scrub the beets before cooking. Beets peel best after
cooking, and they will stain many things they come into contact with.
Wear gloves if you wish to avoid stained hands.

Tender beets can be eaten raw, but they are often cooked before eating
by boiling, steaming, or roasting.
Cooked beets can be sliced and served as a vegetable on one side of a
plate.
** Broccoli, raw
Frozen broccoli can be stored in the freezer for 10-18 months.
You can often save money by purchasing larger bags of frozen
broccoli. Thaw only what you need at a time.
Frozen broccoli is typically available in 3 cuts: spears (stem plus
floret), florets (just the top portion), and chopped (diced stems and
florets). Choose the one that works best for your family’s taste and
budget.

Steam frozen broccoli on the stove until it is a rich, dark green
color - usually 5-8 minutes. Add a dash of seasoning and enjoy!
Broccoli pasta: Add frozen broccoli to the pot of boiling pasta about
three minutes before the end of the cooking time. Season as desired.
Roasted broccoli: Toss frozen broccoli with oil and a sprinkle of
salt. Spread on a baking sheet and roast at 400 degrees F until
browned.
** Carrots, mature, raw
Carrots are in season all year- in winter, spring, summer, and fall
Carrots can be stored in the refrigerator for 2 - 3 weeks from the
date of purchase
Carrots are available fresh, frozen, or canned

Carrot sticks or baby carrots are a great portable snack. Pack them
for work, activities, or when you travel.
Add diced or shredded carrots to your favorite soup, salad, or slaw.
Carrots are perfect for dipping! Try hummus, peanut butter, or a DIY
dip made of yogurt mixed with herbs and spices.
** Collards, raw
Collard greens are in season in spring, winter, and fall. Fruits and
vegetables may cost less when they are in season.
Choose bunches with dark green leaves with no yellowing.
From the date of purchase, fresh collard greens can be stored in the
refrigerator for up to 4 days.
You may be able to save money by purchasing and chopping bunches of
collard greens instead of buying pre-cut bags.

Need a quick side dish? Mix collard greens with chicken broth, onions,
and paprika in a saucepan. Let greens simmer on low heat until ready
to serve.
Top any bowl of soup with a handful of collards and let the heat of
the soup quick steam the greens for an added nutritional boost.
Add chopped collard greens to the pasta pot when pasta is about 5
minutes from being done. Season with a small amount of olive oil and
your favorite herbs and spices.
Collard greens are a great addition to any stir fry. Try them with
garlic, onion, honey, and chicken breast or tofu.
** Cucumber, with peel, raw
Cucumbers are in season in summer. Fruits and vegetables may cost less
when they are in season.
From the date of purchase, cucumbers can be stored in the refrigerator
for 4-6 days.
Choose firm cucumbers with a dark green color.
Did you know that there are nutrients and fiber found in the dark
green skin of a cucumber? So, skip the peeling step and eat the
cucumber with the skin – but don’t forget to wash well.

Slice up a cucumber, then drizzle with lime juice and sprinkle with
chili powder.
Mix finely diced, peeled and seeded cucumber into chicken, shrimp or
tuna salad.
Add cucumber slices to your favorite sandwich or wrap for added
crunch.
Make cucumber canoes for a fun snack. Slice cucumbers in half
lengthwise and scoop the seeds out with a spoon. Fill with cottage
cheese and diced tomatoes.
Pair cucumbers with hummus for a filling and delicious snack.
** String Beans, snap, green, raw, string
Green beans are in season in summer and fall. Fruits and vegetables
may cost less when they are in season.
Green beans can be stored in the refrigerator for up to 5 days from
the date of purchase.
Green beans are available fresh, frozen, and canned.

Sauté green beans in a pan with olive oil and a splash of lemon juice
for an easy side.
Trim off the ends and steam green beans until tender, then toss with
your favorite vinaigrette.
Stir frozen green beans into your favorite soup or stew to boost the
amount of vegetables.

Unopened canned pineapple can be stored in the pantry for 12-18
months. Check the date on the label.
After opening, store in the refrigerator for 5-7 days.
To cut down on added sugars, look for pineapple canned in 100% juice
or water, rather than syrups.

Top yogurt or cottage cheese with canned pineapple for a snack.
Make your own pineapple sorbet! Freeze canned chunks, then blend until
smooth.
Top your chicken sandwich or burger with a canned pineapple ring for a
great sweet-savory combination.

** Cabbage, green, raw
Cabbage is in season in winter, spring, and fall.
From the date of purchase, cabbage can be stored in the refrigerator
for 1-2 weeks.
You can save money by purchasing and chopping heads of cabbage instead
of buying pre-cut bags.

Make a quick slaw with shredded cabbage, oil, vinegar, and spices.
Sauté shredded cabbage with onions and your favorite seasoning until
soft and tender for a delicious side dish.
Add extra crunch to your salads, soups, tacos, or sandwiches by
topping them off with thinly sliced cabbage.
** Potatoes, gold, without skin, raw
Potatoes are in season in fall and winter but can be purchased all
year round.
Potatoes can be stored 1-2 months in the pantry, from the date of
purchase.
Potatoes are available fresh, frozen, and canned.
You can often save money by buying a bag of potatoes, rather than
buying them individually.

Microwaved: Clean the potato and prick several times with a
fork. Microwave on a plate for 10 minutes, turning over halfway
through cooking. Season and enjoy!
Oven roasted: Clean and cut potatoes into 1 inch cubes. Toss in a bowl
with oil and your favorite spices. Bake at 450 degrees F for 30
minutes.
Boiled: Clean and cut potatoes into 1 inch cubes. Boil until you can
easily pierce with a fork. Mix with a bit of unsalted tub margarine
and seasonings.

** Squash, summer, green, zucchini, includes skin, raw
Summer squash is in season in summer. Fruits and vegetables may cost
less when they are in season.
Choose firm squash with no wrinkled skin or soft spots.
Summer squash can be stored up to 2 days at room temperature, and up
to 5 days in the refrigerator. Wash just before using.
There are many types of summer squash, including chayote, cousa,
crookneck, pattypan, and zucchini.

Add steamed summer squash to your favorite pasta sauce and serve over
spaghetti for an easy weeknight meal.
Use a vegetable peeler to create thin shavings of raw zucchini or
crookneck squash that can add crunch to salads or sandwiches.
Sauté sliced summer squash in olive oil and your favorite seasonings
for a quick side dish.

* Legumes and Legume Products
** Beans, Dry, Black (0% moisture)
Canned beans can be stored in the pantry for up to 5 years from the
date of purchase. Check the date on the can.
Once opened, refrigerate beans and use within 4 days.
To cut down on sodium (salt), drain and rinse canned beans in a
colander before using. Some stores may also carry low sodium (salt)
products. Look for “‘less sodium” or “no salt added” on the label.
You may be able to save money by purchasing the store brand or larger
cans of beans. Choose what works best for your family.

Add black beans to eggs and wrap in a tortilla with diced tomatoes and
shredded cheddar cheese (reduced fat) for a delicious breakfast
burrito.
Blend together black beans, salsa, lime juice, cumin, and cilantro to
create a black bean dip. Serve with tortilla chips or raw vegetables.
“Beans and rice” or “rice and beans”... However you say it, black
beans and rice make a great combo and a delicious and nutritious meal.
Make black beans patties mixed with diced bell pepper and your
favorite herbs and spices.
** Beans, Dry, Dark Red Kidney (0% moisture)
Canned beans can be stored in the pantry for up to 5 years from the
date of purchase. Check the date on the can.
Once opened, refrigerate beans and use within 4 days.
To cut down on sodium (salt), drain and rinse canned beans in a
colander before using. Some stores may also carry low sodium (salt)
products. Look for “‘less sodium” or “no salt added” on the label.
You may be able to save money by purchasing the store brand or larger
cans of beans. Choose what works best for your family.

Add kidney beans to your favorite pasta sauce and spoon over whole
wheat spaghetti. Serve with a garden salad or steamed veggies for a
complete meal.  For a quick and easy side, stir together canned corn,
kidney beans (drained and rinsed), and chili powder.  Kidney beans
make a great addition to chili. Whether you prefer chili con carne or
vegetarian chili, stir in kidney beans for added fiber and flavor.
Adding kidney beans to a meal can be a quick way to add protein. Mix
beans with some pico de gallo (or salsa) and greens for a quick taco
salad.
** Lentils, dry
Lentils can be stored in the pantry for up to 1 year from the date of
purchase.
After cooking, store lentils in the refrigerator for up to 5 days.
Lentils are available in most food stores in the dried and canned bean
section.
Unlike dry beans, dry lentils do not have to be pre-soaked and are
quick to cook. Rinse dry lentils before cooking.

Basic cooking directions: combine 1 cup of rinsed dry brown lentils
with 3 cups of water. Bring to a boil, then simmer on low heat for 30
minutes or until tender.  Lentils can be added to or substitute for
meat in chili, tacos, sauces, and meatloaf.  Combine lentils with
rice, vegetables, or pasta to create a meal.
** Peanut butter, creamy
Unopened peanut butter can often be stored in the pantry for up to 2
years. Check the date on the label.
Once opened, peanut butter can be stored in the pantry for 2
months. If the peanut butter is labeled as natural, store it in the
fridge for up to 4 months.
You can often save money by purchasing the store brand of peanut
butter and by purchasing a larger container.

Peanut butter makes a great dip for crunchy fruits and vegetables like
apple and pear slices or sticks of carrot and celery.
Make mini sandwiches of peanut butter and whole wheat crackers for an
easy snack on the go.
Use peanut butter to make a peanut sauce to go with noodles.

** Peanuts, raw
Unopened peanuts can be stored in the pantry until the use-by date on
the package.
Once opened, peanuts can be stored in the pantry for up to 2 weeks or
in the refrigerator for up to 4 weeks.
To reduce sodium (salt), look for dry roasted, unsalted peanuts.
You may be able to save money by buying large containers of
peanuts. Purchase only what you know you can use within the timeframes
above.

Mix peanuts, dried fruit (like raisins), and toasted oat cereal for an
easy and portable trail mix.
Leave peanuts in large pieces or crush to use as a topping for soups,
stews, and salads.
Add a protein-filled crunch to stir-fried vegetables by mixing in
peanuts. Serve over brown rice or whole wheat noodles.
Add some crunch to your yogurt parfait by adding crushed peanuts.

** Common Beans, Dry, Pinto (0% moisture)
Canned beans can be stored in the pantry for up to 5 years from the
date of purchase. Check the date on the can.
Once opened, refrigerate beans and use within 4 days.
To cut down on sodium (salt), drain and rinse canned beans in a
colander before using. Some stores may also carry low sodium (salt)
products. Look for “‘less sodium” or “no salt added” on the label.
You may be able to save money by purchasing the store brand or larger
cans of beans. Choose what works best for your family.

Mash 1 can of pinto beans (drained and rinsed) with chili powder and
garlic powder to taste. Spread on celery sticks and top with salsa for
a crunchy snack.
Make an easy three bean salad. Combine 1 can each of pinto beans,
green beans, kidney beans, with diced onions and tomatoes with your
favorite vinaigrette.
Add pinto beans to soups, stews, chilis or even pasta salads for added
flavor and texture.

* Baked Products
** Bread, whole-wheat, commercially prepared
Bread can be stored in the pantry for about 5 days, or in the freezer
for 3 months.
If bread is on sale, buy an extra loaf and freeze it. When you’re
ready to use the frozen loaf, simply thaw at room temperature or pop a
frozen slice in the toaster.
On the label, look for “whole wheat” or “whole grain” as the first
ingredient listed to choose a whole grain bread.

Top whole wheat toast with nut butter and fruit like sliced bananas or
apples.
Make your own whole grain croutons. Drizzle cubes of bread with oil
and sprinkle with garlic and onion powder. Bake until toasted.
Try a new sandwich idea on wheat bread: roasted veggies and cheese,
tofu and tomato, or hummus and turkey.
* Cereal Grains and Pasta
** Rice, brown, long grain, unenriched, raw
Brown rice can be stored in the pantry for up to 1 year.
Once cooked, store in the refrigerator for 4 - 6 days.
Brown rice comes in various cooking varieties, including instant or
regular. Regular-cook rice may be the least expensive option. Choose
what works best for your family.

Add cooked brown rice to vegetable soup for a quick meal.
Create your own burrito bowl with brown rice, vegetables, your
favorite protein food and top with shredded cheese or plain yogurt
mixed with herbs and seasonings.
Brown rice for breakfast? Yes! Warm it up with milk, raisins, and
cinnamon or try your own creation.
** Corn, sweet, yellow and white kernels,  fresh, raw
Unopened canned corn can be stored in the pantry for 2-5 years from
the date of purchase. After opening, store in the refrigerator for 3-4
days.
Did you know? Canned corn is fully cooked, so it is safe to eat
without further cooking.
Canned vegetables are great to keep on hand. Look for “low sodium” or
“no salt added” on the label, or rinse canned vegetables to reduce
their sodium (salt) content.

Sauté canned corn in a small amount of oil with green chilies, tomato,
and onions for a colorful side dish.
Create a quick pasta salad with canned corn, chopped vegetables, beans
and vinaigrette.
Add corn to soup, chili, salsa, chowder, tacos, burrito bowls.
Combine corn with lima beans to make succotash.
** Flour, corn, yellow, fine meal, enriched
Cornmeal can be stored in an airtight container in a cool dark pantry
for up to 6 months, or in the refrigerator for up to 1 year.
Cornmeal is made from dried corn; it can be either yellow or white.

Cornmeal is a versatile baking ingredient. Use it in muffins, scones,
biscuits, cookies, and cakes.
Use cornmeal to make crispy baked okra bites. Mix cornmeal with
paprika and garlic powder. Roll okra pieces in the mixture, then bake
at 400 degrees F for 25 minutes.
Combine cornmeal, flour, and your favorite seasonings to make a
breading for chicken, pork, or fish.
Try cornmeal as a hot breakfast cereal! Combine 1 cup of water, 1 cup
of cornmeal, and a pinch of salt. Slowly pour the mixture into 3 cups
of boiling water, stirring constantly. Cook until thickened, then
serve with syrup.
** Oats, whole grain, rolled, old fashioned, oatmeal
Dry oatmeal can be stored in the pantry for up to 12 months.
You can often save money by purchasing oatmeal canisters instead of
individual packets.
To cut down on added sugars, look for plain oatmeal and add your own
flavorings at home.

Oatmeal isn’t just for breakfast! Serve as a side dish or mix in
ingredients for a one-dish meal.
Make it sweet: Mix in fruit (fresh, dried, or thawed frozen),
cinnamon, crushed nuts or your favorite nut butter.
Make it savory: Try cooking with egg, green onions, and a sprinkle of
shredded cheese on top.
Oatmeal can replace breadcrumbs in some recipes like meatloaf.
** Pasta, Flour, whole wheat, unenriched
Uncooked dry pasta can be stored in the pantry for up to 1 year.
Once cooked, store in the refrigerator for 3 - 5 days.
On the label, look for “whole grain” or “whole wheat” flour.
You may be able to save money by purchasing the store brand.

When boiling pasta, add frozen veggies during the last 5 minutes for a
colorful one pot dish.
Mix cooked spaghetti with canned tuna, vegetables, oil, and seasonings
for a quick meal.
Make an easy white bean and pasta dish: combine cooked pasta,
drained/rinsed cannellini beans, canned diced tomatoes, canned corn,
and oil. Season as you like.

** Wild rice, dry, raw
Wild rice has long, black whole grains with a nutty flavor and can be
used in many ways.
Wild rice can be stored in the pantry for up to 1 year.
Once cooked, store in the refrigerator for 4 - 6 days.

Wild rice can be cooked and eaten on its own, or can be used in soups,
casseroles, stuffing, or pilafs.
Add cooked wild rice to chicken or vegetable soup for a quick meal.
Create your own rice bowl with cooked wild rice, your favorite
vegetables, and a sprinkle of cheese.

* Dairy and Egg Products
** Buttermilk, low fat
Buttermilk should be refrigerated and must be used within 7-10 days
after opening. Check the expiration date on the container.
Buttermilk can be frozen for up to 3 months from the date of purchase.
Buttermilk is available in several varieties. Look for low-fat or fat
free versions.

Make a simple buttermilk dressing with lemon juice, olive oil, and
herbs. Lightly drizzle on a garden salad packed with fresh vegetables.
Buttermilk works well in marinades because the slight acidity helps to
tenderize meat. Mix with your favorite seasonings and try it for baked
chicken or braised pork.
Buttermilk adds a rich creamy texture and tangy flavor to mashed
potatoes. Try it in place of milk in your favorite mashed potato
recipe.
** Cheese, cheddar
Cheddar cheese can be stored in the fridge for 1 month.
Cheddar cheese can be frozen for 3-4 months from the date of
purchase. Once thawed, use within 3 days.
For shredded cheese, you may be able to save money by purchasing large
bags or extra bags when it’s on sale. Store a reasonable amount for
your family in an airtight container in the fridge, and freeze the
rest of the package.

Try turkey on whole wheat bread with a slice of reduced fat cheddar
cheese for an easy lunch option.
Top whole wheat crackers with small slices of cheese and apple.
Make a quick breakfast sandwich with toasted whole wheat bread,
cheese, and egg.
Sprinkle a bit of cheese on vegetables like steamed broccoli or
brussels sprouts for extra flavor.

** Cheese, cottage, lowfat, 2% milkfat
Cottage cheese can be stored in the fridge for 2 weeks (unopened) or 1
week (opened).
Look for low-fat or fat-free varieties.
If you consume cottage cheese often, you may be able to save money by
purchasing large tubs instead of small or individual
containers. Choose what works best for your family.

Spread cottage cheese on whole wheat crackers and top with your
favorite veggies.
Top cottage cheese with canned peaches, mandarin oranges or sliced
bananas.
Add a spoonful of cottage cheese to scrambled eggs or pasta dishes for
added flavor and protein.
** Milk, reduced fat, fluid, 2% milkfat, with added vitamin A and vitamin D
Milk should be refrigerated and must be used within 7 days after
opening. Check the expiration date on the container.
Milk can be frozen for up to 3 months from the date of purchase.
If milk is on sale, buy a second container. Pour out a small amount to
allow the liquid to expand, and freeze the container. Thaw in the
fridge overnight, shake well, and use within 3 days.

Cook hot cereals like oatmeal or grits in milk to give it a creamy
texture.
Drink milk with meals for a refreshing beverage.
Make or order your tea or coffee with milk.
** Eggs, Grade A, Large, egg whole
Store-bought eggs should be stored in the refrigerator and can be used
for 3-5 weeks from the date of purchase. Check the expiration date on
the carton.
Open the carton and check for cracked eggs before purchasing.
You can often save money by purchasing larger cartons of eggs.

Scramble eggs with peppers, onions and salsa. Serve as is or roll in a
whole wheat tortilla for a portable meal.
Hard cooked eggs make a great snack, or can be added to a salad for
protein. Boil several at once and store in the refrigerator.
Eggs are a versatile protein food that can be included in baked
dishes, sandwiches, omelets, or scrambled into rice and noodle dishes.

** Yogurt, Greek, plain, nonfat
Greek yogurt should be refrigerated and can be stored for 1-2 weeks
from the date of purchase. Check the expiration date on the package.
Freezing Greek yogurt is not recommended.
You can often save money by purchasing larger tubs of Greek yogurt
instead of individual containers. Choose what works best for your
family.

Use plain Greek yogurt to top tacos, pitas, chili, potatoes, and more.
Try Greek yogurt in your favorite tuna salad or pasta salad recipes
for added calcium, tangy flavor, and creamy texture. Use plain Greek
yogurt to make a variety of deliciously smooth dips, spreads, and
salad dressings.
Add canned peaches, pears, or pineapple to your Greek yogurt for a
healthy snack.
** Yogurt, plain, nonfat
Yogurt should be refrigerated and can be stored for 1-2 weeks from the
date of purchase. Check the expiration date on the package.
Yogurt can be frozen for 1-2 months from the date of purchase.
Yogurt can be frozen in its original container. When you’re ready to
use it, just thaw in the fridge overnight, mix well, and serve within
3 days.
You can often save money by purchasing larger tubs of yogurt instead
of individual containers or tubes. Choose what works best for your
family.

Use plain yogurt to top tacos, pitas, chili, potatoes, and more.
Prep fruit and yogurt smoothies for after school or work.
Make a homemade dip with plain yogurt and your favorite herbs and
spices.
Make your own tzatziki sauce with plain yogurt, grated cucumber
(squeezed dry), lemon juice, oil, garlic and spices.

* Finfish and Shellfish Products
** Fish, tuna, light, canned in water, drained solids
Canned tuna can be stored in the pantry for up to 3 years from the
date of purchase.
Look for canned chunk light tuna, which is lower in methylmercury than
albacore.
You can often save money by purchasing the store brand, or by choosing
larger cans or bundles of cans.

Add canned tuna to a garden salad for an easy lunch.
Serve it with pasta. Make a tuna casserole or use it in a macaroni
salad.
Combine canned tuna with plain Greek yogurt or mayonnaise and chopped
celery. Spread the mixture onto whole wheat bread with sliced
cucumbers for a portable sandwich.
** Fish, catfish, farm raised, raw
Catfish is a white fish with a mild flavor that makes it easy to
prepare in many different ways.
You may be able to save money by purchasing frozen fish. Look in the
frozen seafood section of the store.
Thaw frozen fish in the refrigerator. It may take 1-2 days to thaw
completely depending on the size of the fish.

Catfish fillets may be baked, broiled, or grilled.
Try catfish nuggets! Toss pieces of fish fillets in breadcrumbs or
cornmeal and bake for lunch or dinner.
Make your own blackened catfish! Season with paprika and other spices,
then cook on the stovetop. Serve along with brown rice and vegetables
for a complete meal.

** Fish, salmon, Atlantic, farm raised, raw
Salmon is a flaky fish with flesh ranging from orange to dark red in
color.
Salmon is a source of omega-3 fatty acids which, as part of a healthy
diet, may help reduce the risk of heart disease.
You may be able to save money by purchasing frozen fish. Look in the
frozen seafood section of the store.
Thaw frozen fish in the refrigerator. It may take 1-2 days to thaw
completely depending on the size of the fish.

Salmon fillets can be baked, broiled, or grilled.
Season salmon filets with lemon juice and your favorite
seasonings. Heat olive oil in a pan and sear salmon on each side until
the internal temperature reaches 145°F.
Place salmon filets skin side down on foil. Top with a drizzle of oil,
onion slices, and lemon pepper or other seasonings. Bake at 350°F for
15-20 minutes, or until the fish reaches 145°F.
** Fish, Walleye fish
** Fish, haddock, tilapia, farm raised, raw
White fish varieties often have a mild flavor that make them easy to
prepare in many different ways. Choose fish varieties that are lower
in methylmercury, such as catfish, flounder/flatfish, haddock, hake,
mullet, pollock, tilapia, and whiting.
Fresh fish can be stored in the refrigerator for up to 3 days from the
date of purchase, or up to 6 months in the freezer.
You may be able to save money by purchasing frozen fish. Look in the
frozen seafood section of the store.
Thaw frozen fish in the refrigerator. It may take 1-2 days to thaw
completely depending on the size of the fish.

Toss fish fillets in breadcrumbs and bake for lunch or dinner.
Make fish tacos for a delicious and fun meal. Top with diced tomatoes,
onions and a splash of lime juice.
Pan seared fish can be a quick and easy weeknight dinner. Sprinkle
your favorite seasonings on both sides of the fish and cook in a small
amount of olive oil until it reaches an internal temperature of 145°F.

* Poultry Products
** Chicken, broilers or fryers, drumstick, meat only, cooked, braised
** Chicken, thigh, boneless, skinless, raw
Uncooked chicken should be refrigerated and can be stored for 1-2 days
from the date of purchase.
Once cooked, chicken should be refrigerated and used within 3-4 days
or can be frozen and used within 2-6 months.
When buying chicken, drumsticks and thighs are often less expensive
than chicken breasts. Look for chicken breast when it is on sale.
If your store is having a sale on chicken, you can buy extra and
freeze it uncooked for up to 9 months.

Cook all poultry to minimal safe internal temperature of 165° F (74°
C).
Use chicken to make soups and stews. Add canned tomatoes and different
seasonings for endless variety.
Use cooked to top a salad, fill tacos, or in pasta sauce.
Sprinkle seasonings like garlic powder and pepper over chicken before
grilling or broiling it.




