#+title: 如何选购新（二手）手机
#+date: 2025-01-15T19:34:36+01:00
#+lastmod: 2025-01-15T19:34:36+01:00
# ISO 8601 date use output from
# C-u M-! date -Iseconds
#+draft: false
#+tags[]:

本文解释了如何给自己选一部心仪的手机的方法。

# more

对我自己而言，完善的第三方开发群体例如XDA是直接影响到使用体验的。因此，
我应该

选择品牌时只看[[https://xdaforums.com/c/xiaomi.12005/][Xiaomi]]和[[https://xdaforums.com/c/oneplus.11993/][OnePlus]]，因为这两个品牌在国内销量大，二手市场价
格便宜。而且他们使用高通芯片，利于第三方开发。

其他品牌存在的问题：

- 三星：不使用高通芯片
- 联想，摩托：国内销量小，二手机器难找。找到了价格也虚高。
- 谷歌：国内没法用。单卡和eSIM。
- 诺基亚：国内不卖。
- Xiaomi Poco：国内不卖。

访问对应品牌的XDA页面，例如[[https://xdaforums.com/c/xiaomi.12005/][Xiaomi]] [[https://xdaforums.com/c/oneplus.11993/][OnePlus]]，确认每个型号的发帖数量。大于30k发帖
的、不老于6年以上(newer than inclusive 2019)的型号可以考虑。作为对比，当前<2025-01-15 Wed>：
| Model               | Comments | Release    |
|---------------------+----------+------------|
| OnePlus 6 (for ref) | 146k     | May 2018   |
| Redmi Note 10 Pro   | 31k      | March 2021 |
| Redmi K40           | 47k      | March 2021 |
| OnePlus 9 Pro       | 51k      | March 2021 |
| OnePlus 8T          | 34k      | Oct 2020   |

再访问每个机型的Development版块：因为上面的统计包含非Dev内容，真正的
Dev内容可能很少。
| Model               | Comments | Dev     |
|---------------------+----------+---------|
| OnePlus 6 (for ref) | 146k     | [[https://xdaforums.com/f/oneplus-6-6t-cross-device-development.9653/][3 pages]] |
| Redmi Note 10 Pro   | 31k      | [[https://xdaforums.com/f/redmi-note-10-pro.12117/?prefix_id=33][6 pages]] |
| Redmi K40           | 47k      | [[https://xdaforums.com/f/xiaomi-poco-f3-xiaomi-mi-11x-redmi-k40.12161/?prefix_id=33][6 pages]] |
| OnePlus 9 Pro       | 51k      | [[https://xdaforums.com/f/oneplus-9-pro.12153/?prefix_id=33][5 pages]] |
| OnePlus 8T          | 34k      | [[https://xdaforums.com/f/oneplus-8t-roms-kernels-recoveries-other-deve.11587/][5 pages]] |

最后筛选有OLED屏幕的、非曲面屏机型。最好有耳机孔。

小米机器解锁BL需要Windows和小米账号，需要回答问题。不方便。
直接买 *小米解锁机* 。

#+begin_quote
I also installed the Xiaomi Community App, changed the Region to
Global in Order to see the option "Unlock Bootloader" in the "ME"
Menu. I am logged in with an account that has been used for more than
30 days (I had a Poco F1 before for several years and used that Xiaomi
account as well with it before), but every time i click on the "apply
for unlock" option, it tells me "application quota limit reached,
please wait until xxx time and try again" This already happened 2
times. The first time it said i shall try again on the 14.01.2025 0:00
European Time, so i did that and pressed on the apply button again,
only for it to tell me that i shall now wait until the 15.01.2025 0:00
European Time.

from [[https://xdaforums.com/t/problems-with-unlocking-bootloader-of-poco-f3-hyperos-1-0-2-0-application-quota-limit-reached-try-again-at-time-shows-up-every-time.4713519/][BL unlock trouble Xiaomi]]
#+end_quote


Redmi Note 10 Pro的XDA论坛上只有国际版高通版本的。咸鱼上是国内MTK的，
还有虚焊通病，随时变砖。

* Conclusion

告诉爸爸在咸鱼上买红米K40(非K40s)了。看看到货后怎么样。
